---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":4:{s:5:\"title\";s:18:\"Zatar's Client API\";s:11:\"description\";s:60:\"Interactive
  Documentation for Zatar's Client Application API\";s:7:\"version\";s:5:\"1.0.0\";s:7:\"contact\";O:8:\"stdClass\":1:{s:4:\"name\";s:20:\"developers@zatar.com\";}}"
host: integration.zatar.com
basePath: /v1
paths:
  /users:
    post:
      summary: Create a new user account
      description: A user (or end user) is a consumer of Zatar that either has an
        active account or is in the process of setting one up. A user can be created,
        retrieved, and updated.
      security:
      - OAuth:
        - create
      tags:
      - Users
    get:
      summary: Retrieve your user account data
      description: Retrieve the meta-data associated with your user profile.
      security:
      - OAuth:
        - read
      tags:
      - Users
  /users/{user_id}:
    put:
      summary: Change the profile data in your account.
      description: Change the profile data in your account.
      operationId: putUserID
      security:
      - OAuth:
        - update
      tags:
      - Users
    get:
      summary: Retrieve your user account data
      description: Retrieve the meta-data associated with your user profile.
      operationId: getUserID
      security:
      - OAuth:
        - read
      tags:
      - Users
  /authentokens:
    post:
      summary: Create a new authentication token
      description: Create a new authentication token by doing an HTTP POST.
      operationId: getAuthentoken
      security:
      - OAuth:
        - create
      tags:
      - Authentication
  /authentokens/{token_resource_id}:
    get:
      summary: Verify that a token is valid (not expired)
      description: Verify that a token is valid (not expired).
      operationId: getAuthentoken
      security:
      - OAuth:
        - read
      tags:
      - Authentication
  /passwordtokens:
    post:
      summary: Reset your password
      description: Reset your password
      operationId: postPasswordTokenoken
      security:
      - OAuth:
        - create
      tags:
      - Users
      - Authentication
  /passwordtokens/{password_token_id}:
    get:
      summary: Verify a password reset token is still valid and has not expired
      description: Verify a password reset token is still valid and has not expired
      operationId: getInvitationToken
      security:
      - OAuth:
        - read
      tags:
      - Users
      - Authentication
  /invitetokens:
    post:
      summary: Create an invitation token
      description: Create an invitation token
      operationId: postInvitationYoken
      security:
      - OAuth:
        - create
      tags:
      - Users
  /invitetokens/{invitation_token_id}:
    get:
      summary: Verify the invtation is still valid and has not expired
      description: Verify the invtation is still valid and has not expired
      operationId: getInvitationToken
      security:
      - OAuth:
        - read
      tags:
      - Users
  /worlds:
    get:
      summary: Retrieve a collection of worlds
      description: Retrieve a collection of worlds via HTTP GET
      operationId: getWorlds
      security:
      - OAuth:
        - read
      tags:
      - Worlds
  /worlds/{world_id}:
    put:
      summary: Change some of the resources the world can contain
      description: Currently only name of the world can be changed. Invite a user
        to join a world does not use PUT. Transferring ownership of a world is currently
        not supported. The creator of the world remains the only owner.
      security:
      - OAuth:
        - update
      tags:
      - Worlds
    get:
      summary: Retrieve a specific world
      description: Retrieves a world resource and its associated resources.
      tags:
      - Worlds
      security:
      - OAuth:
        - read
  /avatardefinitions:
    post:
      operationId: avatarDefinitions
      tags:
      - Avatars
      summary: NEED SUMMARY
      description: NEED DESCRIPTION
      security:
      - OAuth:
        - create
    get:
      summary: Retrieve a collection of avatardefinitions
      description: 'Retrieve a collection of avatardefinitions with an HTTP GET.This
        would retrieve all the publicly available avatar definitions and the avatar
        definitions from all the worlds that the user has read permissions on. '
      operationId: getAvatarDefinition
      tags:
      - Avatars
      security:
      - OAuth:
        - read
  /avatardefinitions/required:
    get:
      summary: List of required items in an Avatar defintions.
      description: 'Retrieve a list of the required attributes that must exist in
        new Avatar defintions. '
      operationId: AvatarDefinitionsRequiredGet
      tags:
      - Avatars
      security:
      - OAuth:
        - read
  /avatardefinitions/{avatar_defintion_id}:
    get:
      summary: Retrieve a specific avatar definition
      description: Retrieve a specific avatar definition with an HTTP GET. The user
        only has access to public avatar definitions and the avatar definitions belonging
        to worlds that the user has read permissions on.
      operationId: getAvatarDefinition
      tags:
      - Avatars
      security:
      - OAuth:
        - read
    delete:
      summary: Deletes a specific avatar definition
      description: Deletes a specific avatar definition with an HTTP GET. The user
        only has access to public avatar definitions and the avatar definitions belonging
        to worlds that the user has read permissions on.
      operationId: getAvatarDefinition
      security:
      - OAuth:
        - delete
      tags:
      - Avatars
  /worlds/{world_id}/avatars:
    post:
      operationId: avatars
      tags:
      - Avatars
      summary: Create a new device avatar
      description: Create a new device avatar by registering a source and automatically
        pairing it to an avatar definition with an HTTP POST
      security:
      - OAuth:
        - create
    get:
      summary: Retrieve a collection of avatars in specific world
      description: Retrieve a collection of avatars from a user's account private
        world by performing an HTTP GET.
      tags:
      - Avatars
      security:
      - OAuth:
        - read
  /worlds/{world_id}/avatars/{avatar_id}:
    put:
      operationId: avatar
      tags:
      - Avatars
      summary: Change properties or send commands to an avatar
      description: Some of the properties of an avatar can be changed using PUT. Sending
        commands is also possible doing a PUT
      security:
      - OAuth:
        - update
    get:
      summary: Retrieve an avatar for a single device
      description: Retrieve an avatar for a single device by performing an HTTP GETand
        including the avatarId.
      tags:
      - Avatars
      security:
      - OAuth:
        - read
    delete:
      operationId: avatarDelete
      tags:
      - Avatars
      summary: Permanently delete a device avatar
      description: Permanently delete a device avatar and remove it from the database
        by performing an HTTP DELETE and including the avatar_id
      security:
      - OAuth:
        - delete
  /worlds/{world_id}/avatars/{avatar_id}/history:
    get:
      summary: Retrieve history of an avatar for a single device
      description: Retrieve the history of an avatar for a single device by performing
        an HTTP GET and including the avatar_id.
      tags:
      - Avatars
      - Avatar History
      security:
      - OAuth:
        - read
  /worlds/{world_id}/avatars/{avatar_id}/jobs:
    get:
      summary: Retrieve a collection of jobs of an avatar
      description: Retrieves all the non expired jobs associated with an avatar by
        performing an HTTP GET.
      tags:
      - Avatars
      - Jobs
      security:
      - OAuth:
        - read
  /worlds/{world_id}/avatars/{avatar_id}/jobs/{job_id}:
    get:
      summary: Retrieve a specific jobs of an avatar
      description: Retrieves a specific non expired job associated with an avatar
        by performing an HTTP GET.
      tags:
      - Avatars
      - Jobs
      security:
      - OAuth:
        - read
  /worlds/{world_id}/avatars/eventdefinitions:
    post:
      operationId: avatarsEventDefinitionsPost
      tags:
      - Avatars
      - Events
      summary: ??
      description: ??
      security:
      - OAuth:
        - create
    get:
      operationId: avatarsEventDefinitionsGet
      tags:
      - Avatars
      - Events
      security:
      - OAuth:
        - read
      summary: ??
      description: ??
  /worlds/{world_id}/avatars/eventdefinitions/{event_definition_id}:
    delete:
      operationId: avatarsEventDefinitionDeleteGet
      tags:
      - Avatars
      - Events
      summary: Delete a specific avatar event defintion within a specific world.
      description: Delete a specific avatar event defintion within a specific world.
      security:
      - OAuth:
        - delete
    get:
      operationId: avatarsEventDefinitionGet
      tags:
      - Avatars
      - Events
      summary: ??
      description: ??
      security:
      - OAuth:
        - read
    put:
      operationId: avatarsEventDefinitionPut
      tags:
      - Avatars
      - Events
      summary: ??
      description: ??
      security:
      - OAuth:
        - update
  /worlds/{world_id}/avatars/{avatar_id}/eventdefinitions:
    post:
      operationId: avatarEventDefinitionsPost
      tags:
      - Avatars
      - Events
      summary: ??
      description: ??
      security:
      - OAuth:
        - create
    get:
      operationId: avatarEventDefinitionsGet
      tags:
      - Avatars
      - Events
      summary: ??
      description: ??
      security:
      - OAuth:
        - read
  /worlds/{world_id}/avatars/{avatar_id}/eventdefinitions/{event_definition_id}:
    delete:
      operationId: avatarEventDefinitionDeleteGet
      tags:
      - Avatars
      - Events
      summary: Delete a specific avatar event defintion within a specific world.
      description: Delete a specific avatar event defintion within a specific world.
      security:
      - OAuth:
        - delete
    get:
      operationId: avatarEventDefinitionGet
      tags:
      - Avatars
      - Events
      summary: ??
      description: ??
      security:
      - OAuth:
        - read
    put:
      operationId: avatarEventDefinitionPut
      tags:
      - Avatars
      - Events
      summary: ??
      description: ??
      security:
      - OAuth:
        - update
  /worlds/{world_id}/avatars/events:
    get:
      operationId: avatarsEventsGet
      tags:
      - Avatars
      - Events
      summary: Get events across all the avatars in a world.
      description: Displays events of event definitions that are defined at the scope
        avatars.
      security:
      - OAuth:
        - read
  /worlds/{world_id}/avatars/{avatar_id}/events:
    get:
      operationId: avatarEventsGet
      tags:
      - Avatars
      - Events
      summary: Display events that are triggered on a specific avatar.
      description: Display events that are triggered on a specific avatar.
      security:
      - OAuth:
        - read
  /worlds/{world_id}/avatars/{avatar_id}/events/{event_id}:
    get:
      operationId: avatarEventGet
      tags:
      - Avatars
      - Events
      summary: Retrieve a specific event that was triggered on a specific avatar.
      description: Retrieve a specific event that was triggered on a specific avatar.
      security:
      - OAuth:
        - read
  /worlds/{world_id}/notifications:
    post:
      operationId: notificationsPost
      tags:
      - Notifications
      summary: Creates a Notification of the specified type.
      description: Creates a Notification of the specified type.
      security:
      - OAuth:
        - create
    get:
      operationId: notificationsGet
      tags:
      - Notifications
      summary: Retrieves all notifications in the specified world.
      description: Retrieves all notifications in the specified world.
      security:
      - OAuth:
        - read
  /worlds/{world_id}/notifications/{notification_id}:
    get:
      operationId: notificationGet
      tags:
      - Notifications
      summary: Retrieves the specified notification.
      description: Retrieves the specified notification.
      security:
      - OAuth:
        - read
    put:
      operationId: notificationPut
      tags:
      - Notifications
      summary: Updates the specified Notification.
      description: Updates the specified Notification.
      security:
      - OAuth:
        - update
    delete:
      operationId: notificationDelete
      tags:
      - Notifications
      summary: Delete the specified notification.
      description: Delete the specified notification.
      security:
      - OAuth:
        - delete
  /worlds/{world_id}/avatargroups:
    post:
      operationId: avatarGroupsPost
      tags:
      - Avatars
      - Groups
      summary: Creates an avatar group
      description: Creates an avatar group (static or dynamic based on the content
        of the payload) with an HTTP POST
      security:
      - OAuth:
        - create
    get:
      operationId: avatarGroupsPost
      tags:
      - Avatars
      - Groups
      summary: Retrieve a collection of avatar groups
      description: Retrieve a collection of avatar groups via a HTTP GET
      security:
      - OAuth:
        - read
  /worlds/{world_id}/avatargroups/{avatargroup_id}:
    put:
      operationId: avatarGroupPut
      tags:
      - Avatars
      - Groups
      summary: Change the name of a group
      description: Change the name of a group with an HTTP PUT
      security:
      - OAuth:
        - update
    get:
      operationId: avatarGroupGet
      tags:
      - Avatars
      - Groups
      summary: Retrieve a specific Avatar group
      description: Retrieve a specific Avatar group with an HTTP PUT
      security:
      - OAuth:
        - read
    delete:
      operationId: avatarGroupDelete
      tags:
      - Avatars
      - Groups
      summary: Delete a specific Avatar group
      description: Delete a specific Avatar group with an HTTP DELETE
      security:
      - OAuth:
        - delete
  /worlds/{world_id}/avatargroups/{avatargroup_id}/avatars:
    post:
      operationId: avatarGroupAvatarPost
      tags:
      - Avatars
      - Groups
      summary: Adds an avatar to an avatar group
      description: Adds an avatar to an avatar group by performing an HTTP POST.
      security:
      - OAuth:
        - create
    get:
      operationId: avatarGroupAvatarsGet
      tags:
      - Avatars
      - Groups
      summary: Retrieve all the Avatars associated with an Avatar group
      description: Retrieve all the avatars associated with an Avatar Group with an
        HTTP GET.
      security:
      - OAuth:
        - read
  /worlds/{world_id}/{avatargroup_id}/avatars/{avatar_id}:
    delete:
      operationId: avatarGroupDelete
      tags:
      - Avatars
      - Groups
      summary: Delete an Avatar from a group
      description: Deletes a device permanently from a group by performing an HTTP
        DELETE
      security:
      - OAuth:
        - delete
  /worlds/{world_id}/avatarprofiles:
    post:
      operationId: avatarProfilesPost
      tags:
      - Avatars
      - Profiles
      summary: Create a new avatar profile
      description: Create a new avatar profile by performing an HTTP POST
      security:
      - OAuth:
        - create
    get:
      operationId: avatarProfilesGet
      tags:
      - Avatars
      - Profiles
      summary: Get all avatar profiles within a world
      description: Get all avatar profiles within a specific world by performing an
        HTTP GET.
      security:
      - OAuth:
        - read
  /worlds/{world_id}/avatarprofiles/{avatarprofile_id}:
    put:
      operationId: avatarProfilePut
      tags:
      - Avatars
      - Profiles
      summary: Modify an existing avatar profile
      description: Modify an existing avatar profile by doing an HTTP PUT. Only existing
        settings can be modified. No new settings can be added with a PUT. The user
        issuing this request requires Update permission within the world the avatar
        profile has been created. This operation will issue an implicit 'apply settings'
        command to all avatars currently associated to this avatar profile. This is
        required to maintain consistency between avatars and the associated avatar
        profile.
      security:
      - OAuth:
        - update
    get:
      operationId: avatarProfileGet
      tags:
      - Avatars
      - Profiles
      summary: Retrieve a specific avatar profile within a specific world.
      description: Retrieve a specific avatar profile within a specific world.
      security:
      - OAuth:
        - read
    delete:
      operationId: avatarProfileGet
      tags:
      - Avatars
      - Profiles
      summary: Delete a specific avatar profile within a specific world.
      description: Delete a specific avatar profile within a specific world.
      security:
      - OAuth:
        - delete
  /worlds/{world_id}/avatarprofiles/{avatarprofile_id}/avatars:
    get:
      operationId: avatarProfileAvatarGet
      tags:
      - Avatars
      - Profiles
      summary: Retrieve all avatars in a profile within a specific world.
      description: Retrieves all the avatars associated with an Avatar Profile with
        an HTTP GET.
      security:
      - OAuth:
        - read
  /avatardefinitions/{avatar_defintion_id}/firmware:
    get:
      summary: Retrieve a collection of avatar definition firmware
      description: All existing firmwares for an avatar definition Id can be retrieved
        by performing an HTTP GET.
      operationId: getAvatarDefinitionFirmwares
      security:
      - OAuth:
        - read
      tags:
      - Avatars
      - Firmware
  /avatardefinitions/{avatar_definition_id}/firmware/{firmware_id}:
    get:
      summary: Retrieve a specific avatar definition firmware
      description: Specific firmware versions associated with an avatar definition
        Id can be retrieved by performing an HTTP GET.
      operationId: getAvatarDefinitionFirmware
      security:
      - OAuth:
        - read
      tags:
      - Avatars
      - Firmware
  /worlds/{world_id}/discoverabledevices:
    post:
      operationId: discoverabledevicesPost
      tags:
      - Discoverable Devices
      summary: Create a new discoverable device resource by performing an HTTP POST.
      description: Create a new discoverable device resource by performing an HTTP
        POST.
      security:
      - OAuth:
        - create
  /worlds/{world_id}/discoverabledevices/{discoverabledevice_id}:
    get:
      operationId: discoverabledeviceGet
      tags:
      - Discoverable Devices
      summary: Retrieve discoverable device resource.
      description: Retrieve discoverable device resource.
      security:
      - OAuth:
        - read
schemes:
- https
...
