---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":5:{s:5:\"title\";s:20:\"Digital Registry Api\";s:11:\"description\";s:0:\"\";s:14:\"termsOfService\";s:0:\"\";s:7:\"contact\";O:8:\"stdClass\":1:{s:5:\"email\";s:18:\"contact@mysite.com\";}s:7:\"version\";s:5:\"1.0.0\";}"
host: api.digital-registry.dk
basePath: /
paths:
  /contact/{identifier}:
    get:
      tags:
      - contact
      summary: Get contact by identifier, either CPR or CVR
      description: Return contact.
      operationId: contact
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /contact:
    post:
      tags:
      - contact
      summary: Create contact.
      description: Create a contact.
      operationId: contact-create
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /search:
    get:
      tags:
      - contact
      summary: Get contact by identifier, either CPR or CVR
      description: Return list of contacts.
      operationId: search
      security:
      - basic-auth:
        - read:contact
  /contact/register:
    post:
      tags:
      - contact
      summary: Create contact resource.
      description: Register a contact including media and subscription values.
      operationId: contact-register
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /contact/{identifier}/logs:
    get:
      tags:
      - contact
      summary: Get contact logs.
      description: Get contact logs.
      operationId: contact-logs
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /contact/{identifier}/medias:
    get:
      tags:
      - contact:media
      summary: Get contact medias
      description: Get contact medias.
      operationId: contact-medias
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
    post:
      tags:
      - contact:media
      summary: Create a contact media
      description: Create contact media.
      operationId: contact-medias-create
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /contact/{identifier}/medias/{media_id}:
    delete:
      tags:
      - contact:media
      summary: Delete a contact media
      description: Delete contact media.
      operationId: contact-medias-delete
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /contact/{identifier}/medias/{media_id}/:
    put:
      tags:
      - contact:media
      summary: Update a contact media
      description: Update contact media.
      operationId: contact-medias-update
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /contact/{identifier}/media-subscriptions:
    post:
      tags:
      - contact:media-subscription
      summary: Create a contact media subscriptions
      description: Create contact media.
      operationId: contact-medias-create
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /contact/{identifier}/media-subscriptions/{media_subscription_id}:
    delete:
      tags:
      - contact:media-subscription
      summary: Delete a contact media subscriptions
      description: Delete contact media.
      operationId: contact-medias-delete
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /contact/{identifier}/subscriptions:
    get:
      tags:
      - contact:subscription
      summary: Get contact subscriptions
      description: Get contact subscriptions.
      operationId: contact-subscription
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
    post:
      tags:
      - contact:subscription
      summary: Create a contact subscription
      description: Create contact subscription.
      operationId: contact-subscription-create
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /contact/{identifier}/subscriptions/{subscription_id}:
    get:
      tags:
      - contact:subscription
      summary: Get contact subscriptions
      description: Get contact subscriptions.
      operationId: contact-subscription-get
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
    put:
      tags:
      - contact:subscription
      summary: Update a contact subscription
      description: Create contact subscription.
      operationId: contact-subscription-update
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
    delete:
      tags:
      - contact:subscription
      summary: Delete a contact subscription
      description: Delete contact subscription.
      operationId: contact-medias-delete
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /contact/{identifier}/subscriptions/{subscription_id}/accept-terms:
    put:
      tags:
      - contact:subscription
      summary: Accept subscription terms.
      description: Accept subscription terms.
      operationId: contact-subscription-accept-terms
      security:
      - nemId:
        - write:contact
        - read:contact
        basic-auth:
        - read:contact
  /subscription-types:
    get:
      tags:
      - subscription-types
      summary: List subscription types.
      description: List subscription types.
      operationId: subscription-types
      security:
      - nemId:
        - read:contact
        basic-auth:
        - read:contact
  /terms:
    get:
      tags:
      - term
      summary: Get terms
      description: Get terms.
      operationId: terms
      security:
      - nemId:
        - read:contact
        basic-auth:
        - read:contact
  /terms/{term_id}:
    get:
      tags:
      - term
      summary: Get term
      description: Get term.
      operationId: term
      security:
      - nemId:
        - read:contact
        basic-auth:
        - read:contact
schemes:
- http
- https
...
