---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":10:{s:7:\"contact\";O:8:\"stdClass\":2:{s:4:\"name\";s:6:\"Google\";s:3:\"url\";s:18:\"https://google.com\";}s:11:\"description\";s:59:\"Provides
  access to information about profiles and contacts.\";s:5:\"title\";s:13:\"Google
  People\";s:7:\"version\";s:2:\"v1\";s:23:\"x-apiClientRegistration\";O:8:\"stdClass\":1:{s:3:\"url\";s:37:\"https://console.developers.google.com\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:116:\"https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png\";}s:8:\"x-origin\";a:1:{i:0;O:8:\"stdClass\":4:{s:9:\"converter\";O:8:\"stdClass\":2:{s:3:\"url\";s:45:\"https://github.com/lucybot/api-spec-converter\";s:7:\"version\";s:5:\"2[...]"
host: people.googleapis.com
basePath: /
paths:
  /v1/contactGroups:
    get:
      description: List all contact groups owned by the authenticated user. Members
        of thencontact groups are not populated.
      operationId: people.contactGroups.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      - Oauth2:
        - https://www.googleapis.com/auth/contacts.readonly
      tags:
      - contactGroups
    post:
      description: Create a new contact group owned by the authenticated user.
      operationId: people.contactGroups.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      tags:
      - contactGroups
  /v1/contactGroups:batchGet:
    get:
      description: Get a list of contact groups owned by the authenticated user by
        specifyingna list of contact group resource names.
      operationId: people.contactGroups.batchGet
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      - Oauth2:
        - https://www.googleapis.com/auth/contacts.readonly
      tags:
      - contactGroups
  /v1/people:batchGet:
    get:
      description: Provides information about a list of specific people by specifying
        a listnof requested resource names. Use `people/me` to indicate the authenticatednuser.n<br>nThe
        request throws a 400 error if 'personFields' is not specified.
      operationId: people.people.getBatchGet
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      - Oauth2:
        - https://www.googleapis.com/auth/contacts.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/plus.login
      - Oauth2:
        - https://www.googleapis.com/auth/user.addresses.read
      - Oauth2:
        - https://www.googleapis.com/auth/user.birthday.read
      - Oauth2:
        - https://www.googleapis.com/auth/user.emails.read
      - Oauth2:
        - https://www.googleapis.com/auth/user.phonenumbers.read
      - Oauth2:
        - https://www.googleapis.com/auth/userinfo.email
      - Oauth2:
        - https://www.googleapis.com/auth/userinfo.profile
      tags:
      - people
  /v1/people:createContact:
    post:
      description: Create a new contact and return the person resource for that contact.
      operationId: people.people.createContact
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      tags:
      - people
  /v1/{resourceName}:
    delete:
      description: Delete an existing contact group owned by the authenticated user
        bynspecifying a contact group resource name.
      operationId: people.contactGroups.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      tags:
      - contactGroups
    get:
      description: Get a specific contact group owned by the authenticated user by
        specifyingna contact group resource name.
      operationId: people.contactGroups.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      - Oauth2:
        - https://www.googleapis.com/auth/contacts.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/plus.login
      - Oauth2:
        - https://www.googleapis.com/auth/user.addresses.read
      - Oauth2:
        - https://www.googleapis.com/auth/user.birthday.read
      - Oauth2:
        - https://www.googleapis.com/auth/user.emails.read
      - Oauth2:
        - https://www.googleapis.com/auth/user.phonenumbers.read
      - Oauth2:
        - https://www.googleapis.com/auth/userinfo.email
      - Oauth2:
        - https://www.googleapis.com/auth/userinfo.profile
      tags:
      - contactGroups
    put:
      description: Update the name of an existing contact group owned by the authenticatednuser.
      operationId: people.contactGroups.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      tags:
      - contactGroups
  /v1/{resourceName}/connections:
    get:
      description: Provides a list of the authenticated user's contacts merged with
        anynconnected profiles.n<br>nThe request throws a 400 error if 'personFields'
        is not specified.
      operationId: people.people.connections.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      - Oauth2:
        - https://www.googleapis.com/auth/contacts.readonly
      tags:
      - people
  /v1/{resourceName}/members:modify:
    post:
      description: Modify the members of a contact group owned by the authenticated
        user.
      operationId: people.contactGroups.members.modify
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      tags:
      - contactGroups
  /v1/{resourceName}:deleteContact:
    delete:
      description: Delete a contact person. Any non-contact data will not be deleted.
      operationId: people.people.deleteContact
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      tags:
      - people
  /v1/{resourceName}:updateContact:
    patch:
      description: Update contact data for an existing contact person. Any non-contact
        datanwill not be modified.nnThe request throws a 400 error if `updatePersonFields`
        is not specified.n<br>nThe request throws a 400 error if `person.metadata.sources`
        is notnspecified for the contact to be updated.n<br>nThe request throws a
        412 error if `person.metadata.sources.etag` isndifferent than the contact's
        etag, which indicates the contact has changednsince its data was read. Clients
        should get the latest person and re-applyntheir updates to the latest person.
      operationId: people.people.updateContact
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/contacts
      tags:
      - people
schemes:
- https
...
