---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":6:{s:11:\"description\";s:225:\"This is a Shoppers
  Catalogue server.\n\n[Learn about Swagger](http://swagger.io) or join the IRC channel
  `#swagger` on irc.freenode.net.\n\nFor this sample, you can use the api key `special-key`
  to test the authorization filters\n\";s:7:\"version\";s:5:\"1.0.0\";s:5:\"title\";s:16:\"Shoppers
  OpenAPI\";s:14:\"termsOfService\";s:29:\"http://helloreverb.com/terms/\";s:7:\"contact\";O:8:\"stdClass\":1:{s:4:\"name\";s:19:\"harjeetss@gmail.com\";}s:7:\"license\";O:8:\"stdClass\":2:{s:4:\"name\";s:10:\"Apache
  2.0\";s:3:\"url\";s:47:\"http://www.apache.org/licenses/LICENSE-2.0.html\";}}"
host: shoppers.io
basePath: /v2
paths:
  /v1/products:
    post:
      tags:
      - product
      summary: Add a new product to the store
      description: ""
      operationId: addProduct
      security:
      - shoppers_auth:
        - write_products
        - read_products
  /v1/products/findByCategory:
    get:
      tags:
      - product
      summary: Finds Products by category
      description: Use category1 for testing.
      operationId: findProductsByCategories
      security:
      - shoppers_auth:
        - write_products
        - read_products
  /v1/products/{productId}:
    get:
      tags:
      - product
      summary: Find product by ID
      description: Returns a product when ID < 10.  ID > 10 or nonintegers will simulate
        API error conditions
      operationId: getProductById
      security:
      - api_key: []
      - shoppers_auth:
        - write_products
        - read_products
    post:
      tags:
      - product
      summary: Updates a product in the store with form data
      description: ""
      operationId: updateProductWithForm
      security:
      - shoppers_auth:
        - write_products
        - read_products
    delete:
      tags:
      - product
      summary: Deletes a product
      description: ""
      operationId: deleteProduct
      security:
      - shoppers_auth:
        - write_products
        - read_products
  /v1/products/{sku}/websites:
    post:
      tags:
      - catalogProductWebsiteLinkRepositoryV1
      description: Assign a product to the website
      operationId: catalogProductWebsiteLinkRepositoryV1SavePost
    put:
      tags:
      - catalogProductWebsiteLinkRepositoryV1
      description: Assign a product to the website
      operationId: catalogProductWebsiteLinkRepositoryV1SavePut
  /v1/products/{sku}/websites/{websiteId}:
    delete:
      tags:
      - catalogProductWebsiteLinkRepositoryV1
      description: Remove the website assignment from the product by product sku
      operationId: catalogProductWebsiteLinkRepositoryV1DeleteByIdDelete
schemes:
- http
...
