---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":5:{s:7:\"contact\";O:8:\"stdClass\":1:{s:5:\"email\";s:15:\"support@quay.io\";}s:11:\"description\";s:181:\"This
  API allows you to perform many of the operations required to work with Quay repositories,
  users, and organizations. You can find out more at <a href=\"https://quay.io\">Quay</a>.\";s:14:\"termsOfService\";s:19:\"https://quay.io/tos\";s:5:\"title\";s:13:\"Quay
  Frontend\";s:7:\"version\";s:2:\"v1\";}"
host: quay.io
basePath: /
paths:
  /api/v1/app/{client_id}:
    get:
      description: Get information on the specified application.
      operationId: getApplicationInformation
      tags:
      - organization
    x-name: endpoints.api.organization.ApplicationInformation
    x-path: /api/v1/app/{client_id}
    x-tag: organization
  /api/v1/discovery:
    get:
      description: List all of the API endpoints available in the swagger API format.
      operationId: discovery
      tags:
      - discovery
    x-name: endpoints.api.discovery.DiscoveryResource
    x-path: /api/v1/discovery
    x-tag: discovery
  /api/v1/entities/{prefix}:
    get:
      description: Get a list of entities that match the specified prefix.
      operationId: getMatchingEntities
      tags:
      - search
    x-name: endpoints.api.search.EntitySearch
    x-path: /api/v1/entities/{prefix}
    x-tag: search
  /api/v1/error/{error_type}:
    get:
      description: Get a detailed description of the error
      operationId: getErrorDescription
      tags:
      - error
    x-name: endpoints.api.error.Error
    x-path: /api/v1/error/{error_type}
    x-tag: error
  /api/v1/find/all:
    get:
      description: Get a list of entities and resources that match the specified query.
      operationId: conductSearch
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - search
    x-name: endpoints.api.search.ConductSearch
    x-path: /api/v1/find/all
    x-tag: search
  /api/v1/find/repositories:
    get:
      description: Get a list of apps and repositories that match the specified query.
      operationId: conductRepoSearch
      tags:
      - search
    x-name: endpoints.api.search.ConductRepositorySearch
    x-path: /api/v1/find/repositories
    x-tag: search
  /api/v1/messages:
    get:
      description: Return a super users messages
      operationId: getGlobalMessages
      tags:
      - globalmessages
    post:
      description: Create a message
      operationId: createGlobalMessage
      security:
      - oauth2_implicit:
        - super:user
      tags:
      - globalmessages
    x-name: endpoints.api.globalmessages.GlobalUserMessages
    x-path: /api/v1/messages
    x-tag: globalmessages
  /api/v1/organization/:
    post:
      description: Create a new organization.
      operationId: createOrganization
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - organization
    x-name: endpoints.api.organization.OrganizationList
    x-path: /api/v1/organization/
    x-tag: organization
  /api/v1/organization/{orgname}:
    delete:
      description: Deletes the specified organization.
      operationId: deleteAdminedOrganization
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - organization
    get:
      description: Get the details for the specified organization
      operationId: getOrganization
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - organization
    put:
      description: Change the details for the specified organization.
      operationId: changeOrganizationDetails
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - organization
    x-name: endpoints.api.organization.Organization
    x-path: /api/v1/organization/{orgname}
    x-tag: organization
  /api/v1/organization/{orgname}/aggregatelogs:
    get:
      description: Gets the aggregated logs for the specified organization.
      operationId: getAggregateOrgLogs
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - logs
    x-name: endpoints.api.logs.OrgAggregateLogs
    x-path: /api/v1/organization/{orgname}/aggregatelogs
    x-tag: logs
  /api/v1/organization/{orgname}/applications:
    get:
      description: List the applications for the specified organization
      operationId: getOrganizationApplications
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - organization
    post:
      description: Creates a new application under this organization.
      operationId: createOrganizationApplication
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - organization
    x-name: endpoints.api.organization.OrganizationApplications
    x-path: /api/v1/organization/{orgname}/applications
    x-tag: organization
  /api/v1/organization/{orgname}/applications/{client_id}:
    delete:
      description: Deletes the application under this organization.
      operationId: deleteOrganizationApplication
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - organization
    get:
      description: Retrieves the application with the specified client_id under the
        specified organization
      operationId: getOrganizationApplication
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - organization
    put:
      description: Updates an application under this organization.
      operationId: updateOrganizationApplication
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - organization
    x-name: endpoints.api.organization.OrganizationApplicationResource
    x-path: /api/v1/organization/{orgname}/applications/{client_id}
    x-tag: organization
  /api/v1/organization/{orgname}/invoices:
    get:
      description: List the invoices for the specified orgnaization.
      operationId: listOrgInvoices
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - billing
    x-name: endpoints.api.billing.OrganizationInvoiceList
    x-path: /api/v1/organization/{orgname}/invoices
    x-tag: billing
  /api/v1/organization/{orgname}/logs:
    get:
      description: List the logs for the specified organization.
      operationId: listOrgLogs
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - logs
    x-name: endpoints.api.logs.OrgLogs
    x-path: /api/v1/organization/{orgname}/logs
    x-tag: logs
  /api/v1/organization/{orgname}/members:
    get:
      description: List the human members of the specified organization.
      operationId: getOrganizationMembers
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - organization
    x-name: endpoints.api.organization.OrganizationMemberList
    x-path: /api/v1/organization/{orgname}/members
    x-tag: organization
  /api/v1/organization/{orgname}/members/{membername}:
    delete:
      description: Removes a member from an organization, revoking all its repositoryn        priviledges
        and removing it from all teams in the organization.
      operationId: removeOrganizationMember
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - organization
    get:
      description: Retrieves the details of a member of the organization.
      operationId: getOrganizationMember
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - organization
    x-name: endpoints.api.organization.OrganizationMember
    x-path: /api/v1/organization/{orgname}/members/{membername}
    x-tag: organization
  /api/v1/organization/{orgname}/prototypes:
    get:
      description: List the existing prototypes for this organization.
      operationId: getOrganizationPrototypePermissions
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - prototype
    post:
      description: Create a new permission prototype.
      operationId: createOrganizationPrototypePermission
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - prototype
    x-name: endpoints.api.prototype.PermissionPrototypeList
    x-path: /api/v1/organization/{orgname}/prototypes
    x-tag: prototype
  /api/v1/organization/{orgname}/prototypes/{prototypeid}:
    delete:
      description: Delete an existing permission prototype.
      operationId: deleteOrganizationPrototypePermission
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - prototype
    put:
      description: Update the role of an existing permission prototype.
      operationId: updateOrganizationPrototypePermission
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - prototype
    x-name: endpoints.api.prototype.PermissionPrototype
    x-path: /api/v1/organization/{orgname}/prototypes/{prototypeid}
    x-tag: prototype
  /api/v1/organization/{orgname}/robots:
    get:
      description: List the organization's robots.
      operationId: getOrgRobots
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - robot
    x-name: endpoints.api.robot.OrgRobotList
    x-path: /api/v1/organization/{orgname}/robots
    x-tag: robot
  /api/v1/organization/{orgname}/robots/{robot_shortname}:
    delete:
      description: Delete an existing organization robot.
      operationId: deleteOrgRobot
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - robot
    get:
      description: Returns the organization's robot with the specified name.
      operationId: getOrgRobot
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - robot
    put:
      description: Create a new robot in the organization.
      operationId: createOrgRobot
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - robot
    x-name: endpoints.api.robot.OrgRobot
    x-path: /api/v1/organization/{orgname}/robots/{robot_shortname}
    x-tag: robot
  /api/v1/organization/{orgname}/robots/{robot_shortname}/permissions:
    get:
      description: Returns the list of repository permissions for the org's robot.
      operationId: getOrgRobotPermissions
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - robot
    x-name: endpoints.api.robot.OrgRobotPermissions
    x-path: /api/v1/organization/{orgname}/robots/{robot_shortname}/permissions
    x-tag: robot
  /api/v1/organization/{orgname}/robots/{robot_shortname}/regenerate:
    post:
      description: Regenerates the token for an organization robot.
      operationId: regenerateOrgRobotToken
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - robot
    x-name: endpoints.api.robot.RegenerateOrgRobot
    x-path: /api/v1/organization/{orgname}/robots/{robot_shortname}/regenerate
    x-tag: robot
  /api/v1/organization/{orgname}/team/{teamname}:
    delete:
      description: Delete the specified team.
      operationId: deleteOrganizationTeam
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - team
    put:
      description: Update the org-wide permission for the specified team.
      operationId: updateOrganizationTeam
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - team
    x-name: endpoints.api.team.OrganizationTeam
    x-path: /api/v1/organization/{orgname}/team/{teamname}
    x-tag: team
  /api/v1/organization/{orgname}/team/{teamname}/invite/{email}:
    delete:
      description: Delete an invite of an email address to join a team.
      operationId: deleteTeamMemberEmailInvite
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - team
    put:
      description: Invites an email address to an existing team.
      operationId: inviteTeamMemberEmail
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - team
    x-name: endpoints.api.team.InviteTeamMember
    x-path: /api/v1/organization/{orgname}/team/{teamname}/invite/{email}
    x-tag: team
  /api/v1/organization/{orgname}/team/{teamname}/members:
    get:
      description: Retrieve the list of members for the specified team.
      operationId: getOrganizationTeamMembers
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - team
    x-name: endpoints.api.team.TeamMemberList
    x-path: /api/v1/organization/{orgname}/team/{teamname}/members
    x-tag: team
  /api/v1/organization/{orgname}/team/{teamname}/members/{membername}:
    delete:
      description: Delete a member of a team. If the user is merely invited to joinn        the
        team, then the invite is removed instead.
      operationId: deleteOrganizationTeamMember
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - team
    put:
      description: Adds or invites a member to an existing team.
      operationId: updateOrganizationTeamMember
      security:
      - oauth2_implicit:
        - org:admin
      tags:
      - team
    x-name: endpoints.api.team.TeamMember
    x-path: /api/v1/organization/{orgname}/team/{teamname}/members/{membername}
    x-tag: team
  /api/v1/organization/{orgname}/team/{teamname}/permissions:
    get:
      description: Returns the list of repository permissions for the org's team.
      operationId: getOrganizationTeamPermissions
      tags:
      - team
    x-name: endpoints.api.team.TeamPermissions
    x-path: /api/v1/organization/{orgname}/team/{teamname}/permissions
    x-tag: team
  /api/v1/plans/:
    get:
      description: List the avaialble plans.
      operationId: listPlans
      tags:
      - billing
    x-name: endpoints.api.billing.ListPlans
    x-path: /api/v1/plans/
    x-tag: billing
  /api/v1/repository:
    get:
      description: Fetch the list of repositories visible to the current user under
        a variety of situations.
      operationId: listRepos
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - repository
    post:
      description: Create a new repository.
      operationId: createRepo
      security:
      - oauth2_implicit:
        - repo:create
      tags:
      - repository
    x-name: endpoints.api.repository.RepositoryList
    x-path: /api/v1/repository
    x-tag: repository
  /api/v1/repository/{repository}:
    delete:
      description: Delete a repository.
      operationId: deleteRepository
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repository
    get:
      description: Fetch the specified repository.
      operationId: getRepo
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - repository
    put:
      description: Update the description in the specified repository.
      operationId: updateRepo
      security:
      - oauth2_implicit:
        - repo:write
      tags:
      - repository
    x-name: endpoints.api.repository.Repository
    x-path: /api/v1/repository/{repository}
    x-tag: repository
  /api/v1/repository/{repository}/aggregatelogs:
    get:
      description: Returns the aggregated logs for the specified repository.
      operationId: getAggregateRepoLogs
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - logs
    x-name: endpoints.api.logs.RepositoryAggregateLogs
    x-path: /api/v1/repository/{repository}/aggregatelogs
    x-tag: logs
  /api/v1/repository/{repository}/build/:
    get:
      description: Get the list of repository builds.
      operationId: getRepoBuilds
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - build
    post:
      description: Request that a repository be built and pushed from the specified
        input.
      operationId: requestRepoBuild
      security:
      - oauth2_implicit:
        - repo:write
      tags:
      - build
    x-name: endpoints.api.build.RepositoryBuildList
    x-path: /api/v1/repository/{repository}/build/
    x-tag: build
  /api/v1/repository/{repository}/build/{build_uuid}:
    delete:
      description: Cancels a repository build.
      operationId: cancelRepoBuild
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - build
    get:
      description: Returns information about a build.
      operationId: getRepoBuild
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - build
    x-name: endpoints.api.build.RepositoryBuildResource
    x-path: /api/v1/repository/{repository}/build/{build_uuid}
    x-tag: build
  /api/v1/repository/{repository}/build/{build_uuid}/logs:
    get:
      description: Return the build logs for the build specified by the build uuid.
      operationId: getRepoBuildLogs
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - build
    x-name: endpoints.api.build.RepositoryBuildLogs
    x-path: /api/v1/repository/{repository}/build/{build_uuid}/logs
    x-tag: build
  /api/v1/repository/{repository}/build/{build_uuid}/status:
    get:
      description: Return the status for the builds specified by the build uuids.
      operationId: getRepoBuildStatus
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - build
    x-name: endpoints.api.build.RepositoryBuildStatus
    x-path: /api/v1/repository/{repository}/build/{build_uuid}/status
    x-tag: build
  /api/v1/repository/{repository}/changetrust:
    post:
      description: Change the visibility of a repository.
      operationId: changeRepoTrust
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repository
    x-name: endpoints.api.repository.RepositoryTrust
    x-path: /api/v1/repository/{repository}/changetrust
    x-tag: repository
  /api/v1/repository/{repository}/changevisibility:
    post:
      description: Change the visibility of a repository.
      operationId: changeRepoVisibility
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repository
    x-name: endpoints.api.repository.RepositoryVisibility
    x-path: /api/v1/repository/{repository}/changevisibility
    x-tag: repository
  /api/v1/repository/{repository}/image/:
    get:
      description: List the images for the specified repository.
      operationId: listRepositoryImages
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - image
    x-name: endpoints.api.image.RepositoryImageList
    x-path: /api/v1/repository/{repository}/image/
    x-tag: image
  /api/v1/repository/{repository}/image/{image_id}:
    get:
      description: Get the information available for the specified image.
      operationId: getImage
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - image
    x-name: endpoints.api.image.RepositoryImage
    x-path: /api/v1/repository/{repository}/image/{image_id}
    x-tag: image
  /api/v1/repository/{repository}/image/{imageid}/security:
    get:
      description: Fetches the features and vulnerabilities (if any) for a repository
        image.
      operationId: getRepoImageSecurity
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - secscan
    x-name: endpoints.api.secscan.RepositoryImageSecurity
    x-path: /api/v1/repository/{repository}/image/{imageid}/security
    x-tag: secscan
  /api/v1/repository/{repository}/logs:
    get:
      description: List the logs for the specified repository.
      operationId: listRepoLogs
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - logs
    x-name: endpoints.api.logs.RepositoryLogs
    x-path: /api/v1/repository/{repository}/logs
    x-tag: logs
  /api/v1/repository/{repository}/manifest/{manifestref}/labels:
    get:
      description: ""
      operationId: listManifestLabels
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - manifest
    post:
      description: Adds a new label into the tag manifest.
      operationId: addManifestLabel
      security:
      - oauth2_implicit:
        - repo:write
      tags:
      - manifest
    x-name: endpoints.api.manifest.RepositoryManifestLabels
    x-path: /api/v1/repository/{repository}/manifest/{manifestref}/labels
    x-tag: manifest
  /api/v1/repository/{repository}/manifest/{manifestref}/labels/{labelid}:
    delete:
      description: Deletes an existing label from a manifest.
      operationId: deleteManifestLabel
      security:
      - oauth2_implicit:
        - repo:write
      tags:
      - manifest
    get:
      description: Retrieves the label with the specific ID under the manifest.
      operationId: getManifestLabel
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - manifest
    x-name: endpoints.api.manifest.ManageRepositoryManifestLabel
    x-path: /api/v1/repository/{repository}/manifest/{manifestref}/labels/{labelid}
    x-tag: manifest
  /api/v1/repository/{repository}/manifest/{manifestref}/security:
    get:
      description: ""
      operationId: getRepoManifestSecurity
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - secscan
    x-name: endpoints.api.secscan.RepositoryManifestSecurity
    x-path: /api/v1/repository/{repository}/manifest/{manifestref}/security
    x-tag: secscan
  /api/v1/repository/{repository}/notification/:
    get:
      description: List the notifications for the specified repository.
      operationId: listRepoNotifications
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repositorynotification
    post:
      description: ""
      operationId: createRepoNotification
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repositorynotification
    x-name: endpoints.api.repositorynotification.RepositoryNotificationList
    x-path: /api/v1/repository/{repository}/notification/
    x-tag: repositorynotification
  /api/v1/repository/{repository}/notification/{uuid}:
    delete:
      description: Deletes the specified notification.
      operationId: deleteRepoNotification
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repositorynotification
    get:
      description: Get information for the specified notification.
      operationId: getRepoNotification
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repositorynotification
    post:
      description: Resets repository notification to 0 failures.
      operationId: resetRepositoryNotificationFailures
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repositorynotification
    x-name: endpoints.api.repositorynotification.RepositoryNotification
    x-path: /api/v1/repository/{repository}/notification/{uuid}
    x-tag: repositorynotification
  /api/v1/repository/{repository}/notification/{uuid}/test:
    post:
      description: Queues a test notification for this repository.
      operationId: testRepoNotification
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repositorynotification
    x-name: endpoints.api.repositorynotification.TestRepositoryNotification
    x-path: /api/v1/repository/{repository}/notification/{uuid}/test
    x-tag: repositorynotification
  /api/v1/repository/{repository}/permissions/team/:
    get:
      description: List all team permission.
      operationId: listRepoTeamPermissions
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - permission
    x-name: endpoints.api.permission.RepositoryTeamPermissionList
    x-path: /api/v1/repository/{repository}/permissions/team/
    x-tag: permission
  /api/v1/repository/{repository}/permissions/team/{teamname}:
    delete:
      description: Delete the permission for the specified team.
      operationId: deleteTeamPermissions
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - permission
    get:
      description: Fetch the permission for the specified team.
      operationId: getTeamPermissions
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - permission
    put:
      description: Update the existing team permission.
      operationId: changeTeamPermissions
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - permission
    x-name: endpoints.api.permission.RepositoryTeamPermission
    x-path: /api/v1/repository/{repository}/permissions/team/{teamname}
    x-tag: permission
  /api/v1/repository/{repository}/permissions/user/:
    get:
      description: List all user permissions.
      operationId: listRepoUserPermissions
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - permission
    x-name: endpoints.api.permission.RepositoryUserPermissionList
    x-path: /api/v1/repository/{repository}/permissions/user/
    x-tag: permission
  /api/v1/repository/{repository}/permissions/user/{username}:
    delete:
      description: Delete the permission for the user.
      operationId: deleteUserPermissions
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - permission
    get:
      description: Get the permission for the specified user.
      operationId: getUserPermissions
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - permission
    put:
      description: Update the perimssions for an existing repository.
      operationId: changeUserPermissions
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - permission
    x-name: endpoints.api.permission.RepositoryUserPermission
    x-path: /api/v1/repository/{repository}/permissions/user/{username}
    x-tag: permission
  /api/v1/repository/{repository}/permissions/user/{username}/transitive:
    get:
      description: Get the fetch the permission for the specified user.
      operationId: getUserTransitivePermission
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - permission
    x-name: endpoints.api.permission.RepositoryUserTransitivePermission
    x-path: /api/v1/repository/{repository}/permissions/user/{username}/transitive
    x-tag: permission
  /api/v1/repository/{repository}/signatures:
    get:
      description: Fetches the list of signed tags for the repository.
      operationId: getRepoSignatures
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - signing
    x-name: endpoints.api.signing.RepositorySignatures
    x-path: /api/v1/repository/{repository}/signatures
    x-tag: signing
  /api/v1/repository/{repository}/tag/:
    get:
      description: ""
      operationId: listRepoTags
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - tag
    x-name: endpoints.api.tag.ListRepositoryTags
    x-path: /api/v1/repository/{repository}/tag/
    x-tag: tag
  /api/v1/repository/{repository}/tag/{tag}:
    delete:
      description: Delete the specified repository tag.
      operationId: deleteFullTag
      security:
      - oauth2_implicit:
        - repo:write
      tags:
      - tag
    put:
      description: Change which image a tag points to or create a new tag.
      operationId: changeTag
      security:
      - oauth2_implicit:
        - repo:write
      tags:
      - tag
    x-name: endpoints.api.tag.RepositoryTag
    x-path: /api/v1/repository/{repository}/tag/{tag}
    x-tag: tag
  /api/v1/repository/{repository}/tag/{tag}/images:
    get:
      description: List the images for the specified repository tag.
      operationId: listTagImages
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - tag
    x-name: endpoints.api.tag.RepositoryTagImages
    x-path: /api/v1/repository/{repository}/tag/{tag}/images
    x-tag: tag
  /api/v1/repository/{repository}/tag/{tag}/restore:
    post:
      description: Restores a repository tag back to a previous image in the repository.
      operationId: restoreTag
      security:
      - oauth2_implicit:
        - repo:write
      tags:
      - tag
    x-name: endpoints.api.tag.RestoreTag
    x-path: /api/v1/repository/{repository}/tag/{tag}/restore
    x-tag: tag
  /api/v1/repository/{repository}/tokens/:
    get:
      description: List the tokens for the specified repository.
      operationId: listRepoTokens
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repotoken
    post:
      description: Create a new repository token.
      operationId: createToken
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repotoken
    x-name: endpoints.api.repotoken.RepositoryTokenList
    x-path: /api/v1/repository/{repository}/tokens/
    x-tag: repotoken
  /api/v1/repository/{repository}/tokens/{code}:
    delete:
      description: Delete the repository token.
      operationId: deleteToken
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repotoken
    get:
      description: Fetch the specified repository token information.
      operationId: getTokens
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repotoken
    put:
      description: Update the permissions for the specified repository token.
      operationId: changeToken
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - repotoken
    x-name: endpoints.api.repotoken.RepositoryToken
    x-path: /api/v1/repository/{repository}/tokens/{code}
    x-tag: repotoken
  /api/v1/repository/{repository}/trigger/:
    get:
      description: List the triggers for the specified repository.
      operationId: listBuildTriggers
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - trigger
    x-name: endpoints.api.trigger.BuildTriggerList
    x-path: /api/v1/repository/{repository}/trigger/
    x-tag: trigger
  /api/v1/repository/{repository}/trigger/{trigger_uuid}:
    delete:
      description: Delete the specified build trigger.
      operationId: deleteBuildTrigger
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - trigger
    get:
      description: Get information for the specified build trigger.
      operationId: getBuildTrigger
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - trigger
    x-name: endpoints.api.trigger.BuildTrigger
    x-path: /api/v1/repository/{repository}/trigger/{trigger_uuid}
    x-tag: trigger
  /api/v1/repository/{repository}/trigger/{trigger_uuid}/activate:
    post:
      description: Activate the specified build trigger.
      operationId: activateBuildTrigger
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - trigger
    x-name: endpoints.api.trigger.BuildTriggerActivate
    x-path: /api/v1/repository/{repository}/trigger/{trigger_uuid}/activate
    x-tag: trigger
  /api/v1/repository/{repository}/trigger/{trigger_uuid}/builds:
    get:
      description: List the builds started by the specified trigger.
      operationId: listTriggerRecentBuilds
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - trigger
    x-name: endpoints.api.trigger.TriggerBuildList
    x-path: /api/v1/repository/{repository}/trigger/{trigger_uuid}/builds
    x-tag: trigger
  /api/v1/repository/{repository}/trigger/{trigger_uuid}/start:
    post:
      description: Manually start a build from the specified trigger.
      operationId: manuallyStartBuildTrigger
      security:
      - oauth2_implicit:
        - repo:admin
      tags:
      - trigger
    x-name: endpoints.api.trigger.ActivateBuildTrigger
    x-path: /api/v1/repository/{repository}/trigger/{trigger_uuid}/start
    x-tag: trigger
  /api/v1/user/:
    get:
      description: Get user information for the authenticated user.
      operationId: getLoggedInUser
      security:
      - oauth2_implicit:
        - user:read
      tags:
      - user
    x-name: endpoints.api.user.User
    x-path: /api/v1/user/
    x-tag: user
  /api/v1/user/aggregatelogs:
    get:
      description: Returns the aggregated logs for the current user.
      operationId: getAggregateUserLogs
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - logs
    x-name: endpoints.api.logs.UserAggregateLogs
    x-path: /api/v1/user/aggregatelogs
    x-tag: logs
  /api/v1/user/logs:
    get:
      description: List the logs for the current user.
      operationId: listUserLogs
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - logs
    x-name: endpoints.api.logs.UserLogs
    x-path: /api/v1/user/logs
    x-tag: logs
  /api/v1/user/robots:
    get:
      description: List the available robots for the user.
      operationId: getUserRobots
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - robot
    x-name: endpoints.api.robot.UserRobotList
    x-path: /api/v1/user/robots
    x-tag: robot
  /api/v1/user/robots/{robot_shortname}:
    delete:
      description: Delete an existing robot.
      operationId: deleteUserRobot
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - robot
    get:
      description: Returns the user's robot with the specified name.
      operationId: getUserRobot
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - robot
    put:
      description: Create a new user robot with the specified name.
      operationId: createUserRobot
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - robot
    x-name: endpoints.api.robot.UserRobot
    x-path: /api/v1/user/robots/{robot_shortname}
    x-tag: robot
  /api/v1/user/robots/{robot_shortname}/permissions:
    get:
      description: Returns the list of repository permissions for the user's robot.
      operationId: getUserRobotPermissions
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - robot
    x-name: endpoints.api.robot.UserRobotPermissions
    x-path: /api/v1/user/robots/{robot_shortname}/permissions
    x-tag: robot
  /api/v1/user/robots/{robot_shortname}/regenerate:
    post:
      description: Regenerates the token for a user's robot.
      operationId: regenerateUserRobotToken
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - robot
    x-name: endpoints.api.robot.RegenerateUserRobot
    x-path: /api/v1/user/robots/{robot_shortname}/regenerate
    x-tag: robot
  /api/v1/user/starred:
    get:
      description: List all starred repositories.
      operationId: listStarredRepos
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - user
    post:
      description: Star a repository.
      operationId: createStar
      security:
      - oauth2_implicit:
        - repo:read
      tags:
      - user
    x-name: endpoints.api.user.StarredRepositoryList
    x-path: /api/v1/user/starred
    x-tag: user
  /api/v1/user/starred/{repository}:
    delete:
      description: Removes a star from a repository.
      operationId: deleteStar
      security:
      - oauth2_implicit:
        - user:admin
      tags:
      - user
    x-name: endpoints.api.user.StarredRepository
    x-path: /api/v1/user/starred/{repository}
    x-tag: user
  /api/v1/users/{username}:
    get:
      description: Get user information for the specified user.
      operationId: getUserInformation
      tags:
      - user
    x-name: endpoints.api.user.Users
    x-path: /api/v1/users/{username}
    x-tag: user
  /userfiles/{file_id}:
    x-name: data.userfiles.UserfilesHandlers
    x-path: /userfiles/{file_id}
    x-tag: userfiles
schemes:
- https
...
