---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":12:{s:7:\"contact\";O:8:\"stdClass\":2:{s:4:\"name\";s:6:\"Google\";s:3:\"url\";s:18:\"https://google.com\";}s:11:\"description\";s:40:\"API
  for working with Fusion Tables data.\";s:5:\"title\";s:13:\"Fusion Tables\";s:7:\"version\";s:2:\"v2\";s:23:\"x-apiClientRegistration\";O:8:\"stdClass\":1:{s:3:\"url\";s:37:\"https://console.developers.google.com\";}s:21:\"x-apisguru-categories\";a:1:{i:0;s:5:\"cloud\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:116:\"https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png\";}s:8:\"x-origin\";a:1:{i:0;O:8:\"stdClass\":4:{s:9:\"[...]"
host: www.googleapis.com
basePath: /fusiontables/v2
paths:
  /query:
    get:
      description: Executes a SQL statement which can be any of n- SELECTn- SHOWn-
        DESCRIBE
      operationId: query.sqlGet
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - query
    post:
      description: Executes a Fusion Tables SQL statement, which can be any of n-
        SELECTn- INSERTn- UPDATEn- DELETEn- SHOWn- DESCRIBEn- CREATE statement.
      operationId: query.sql
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - query
  /tables:
    get:
      description: Retrieves a list of tables a user owns.
      operationId: table.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - table
    post:
      description: Creates a new table.
      operationId: table.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - table
  /tables/import:
    post:
      description: Imports a new table.
      operationId: table.importTable
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - table
  /tables/{tableId}:
    delete:
      description: Deletes a table.
      operationId: table.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - table
    get:
      description: Retrieves a specific table by its ID.
      operationId: table.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - table
    patch:
      description: Updates an existing table. Unless explicitly requested, only the
        name, description, and attribution will be updated. This method supports patch
        semantics.
      operationId: table.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - table
    put:
      description: Updates an existing table. Unless explicitly requested, only the
        name, description, and attribution will be updated.
      operationId: table.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - table
  /tables/{tableId}/columns:
    get:
      description: Retrieves a list of columns.
      operationId: column.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - column
    post:
      description: Adds a new column to the table.
      operationId: column.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - column
  /tables/{tableId}/columns/{columnId}:
    delete:
      description: Deletes the specified column.
      operationId: column.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - column
    get:
      description: Retrieves a specific column by its ID.
      operationId: column.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - column
    patch:
      description: Updates the name or type of an existing column. This method supports
        patch semantics.
      operationId: column.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - column
    put:
      description: Updates the name or type of an existing column.
      operationId: column.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - column
  /tables/{tableId}/copy:
    post:
      description: Copies a table.
      operationId: table.copy
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - table
  /tables/{tableId}/import:
    post:
      description: Imports more rows into a table.
      operationId: table.importRows
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - table
  /tables/{tableId}/refetch:
    post:
      description: Replaces rows of the table with the rows of the spreadsheet that
        is first imported from. Current rows remain visible until all replacement
        rows are ready.
      operationId: table.refetchSheet
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - table
  /tables/{tableId}/replace:
    post:
      description: Replaces rows of an existing table. Current rows remain visible
        until all replacement rows are ready.
      operationId: table.replaceRows
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - table
  /tables/{tableId}/styles:
    get:
      description: Retrieves a list of styles.
      operationId: style.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - style
    post:
      description: Adds a new style for the table.
      operationId: style.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - style
  /tables/{tableId}/styles/{styleId}:
    delete:
      description: Deletes a style.
      operationId: style.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - style
    get:
      description: Gets a specific style.
      operationId: style.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - style
    patch:
      description: Updates an existing style. This method supports patch semantics.
      operationId: style.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - style
    put:
      description: Updates an existing style.
      operationId: style.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - style
  /tables/{tableId}/tasks:
    get:
      description: Retrieves a list of tasks.
      operationId: task.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - task
  /tables/{tableId}/tasks/{taskId}:
    delete:
      description: Deletes a specific task by its ID, unless that task has already
        started running.
      operationId: task.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - task
    get:
      description: Retrieves a specific task by its ID.
      operationId: task.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - task
  /tables/{tableId}/templates:
    get:
      description: Retrieves a list of templates.
      operationId: template.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - template
    post:
      description: Creates a new template for the table.
      operationId: template.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - template
  /tables/{tableId}/templates/{templateId}:
    delete:
      description: Deletes a template
      operationId: template.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - template
    get:
      description: Retrieves a specific template by its id
      operationId: template.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables.readonly
      tags:
      - template
    patch:
      description: Updates an existing template. This method supports patch semantics.
      operationId: template.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - template
    put:
      description: Updates an existing template
      operationId: template.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/fusiontables
      tags:
      - template
schemes:
- https
...
