---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":11:{s:7:\"contact\";O:8:\"stdClass\":2:{s:4:\"name\";s:6:\"Google\";s:3:\"url\";s:18:\"https://google.com\";}s:11:\"description\";s:56:\"View
  Google Search Console data for your verified sites.\";s:5:\"title\";s:14:\"Search
  Console\";s:7:\"version\";s:2:\"v3\";s:23:\"x-apiClientRegistration\";O:8:\"stdClass\":1:{s:3:\"url\";s:37:\"https://console.developers.google.com\";}s:21:\"x-apisguru-categories\";a:1:{i:0;s:6:\"search\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:116:\"https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png\";}s:8:\"x-origin\";a:1:{i:0;O:8:\"stdClass\":4:{s:9:\"converter\";O:8:\"stdClass\":2:{s:3:\"url\";s:45:\"https://github[...]"
host: www.googleapis.com
basePath: /webmasters/v3
paths:
  /sites:
    get:
      description: Lists the user's Search Console sites.
      operationId: webmasters.sites.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters.readonly
      tags:
      - sites
  /sites/{siteUrl}:
    delete:
      description: Removes a site from the set of the user's Search Console sites.
      operationId: webmasters.sites.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      tags:
      - sites
    get:
      description: Retrieves information about specific site.
      operationId: webmasters.sites.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters.readonly
      tags:
      - sites
    put:
      description: Adds a site to the set of the user's sites in Search Console.
      operationId: webmasters.sites.add
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      tags:
      - sites
  /sites/{siteUrl}/searchAnalytics/query:
    post:
      description: Query your data with filters and parameters that you define. Returns
        zero or more rows grouped by the row keys that you define. You must define
        a date range of one or more days.nnWhen date is one of the group by values,
        any days without data are omitted from the result list. If you need to know
        which days have data, issue a broad date range query grouped by date for any
        metric, and see which day rows are returned.
      operationId: webmasters.searchanalytics.query
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters.readonly
      tags:
      - searchanalytics
  /sites/{siteUrl}/sitemaps:
    get:
      description: Lists the sitemaps-entries submitted for this site, or included
        in the sitemap index file (if sitemapIndex is specified in the request).
      operationId: webmasters.sitemaps.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters.readonly
      tags:
      - sitemaps
  /sites/{siteUrl}/sitemaps/{feedpath}:
    delete:
      description: Deletes a sitemap from this site.
      operationId: webmasters.sitemaps.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      tags:
      - sitemaps
    get:
      description: Retrieves information about a specific sitemap.
      operationId: webmasters.sitemaps.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters.readonly
      tags:
      - sitemaps
    put:
      description: Submits a sitemap for a site.
      operationId: webmasters.sitemaps.submit
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      tags:
      - sitemaps
  /sites/{siteUrl}/urlCrawlErrorsCounts/query:
    get:
      description: Retrieves a time series of the number of URL crawl errors per error
        category and platform.
      operationId: webmasters.urlcrawlerrorscounts.query
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters.readonly
      tags:
      - urlcrawlerrorscounts
  /sites/{siteUrl}/urlCrawlErrorsSamples:
    get:
      description: Lists a site's sample URLs for the specified crawl error category
        and platform.
      operationId: webmasters.urlcrawlerrorssamples.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters.readonly
      tags:
      - urlcrawlerrorssamples
  /sites/{siteUrl}/urlCrawlErrorsSamples/{url}:
    delete:
      description: Marks the provided site's sample URL as fixed, and removes it from
        the samples list.
      operationId: webmasters.urlcrawlerrorssamples.markAsFixed
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      tags:
      - urlcrawlerrorssamples
    get:
      description: Retrieves details about crawl errors for a site's sample URL.
      operationId: webmasters.urlcrawlerrorssamples.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters
      - Oauth2:
        - https://www.googleapis.com/auth/webmasters.readonly
      tags:
      - urlcrawlerrorssamples
schemes:
- https
...
