---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":11:{s:7:\"contact\";O:8:\"stdClass\":2:{s:4:\"name\";s:6:\"Google\";s:3:\"url\";s:18:\"https://google.com\";}s:11:\"description\";s:44:\"Interacts
  with Glass users via the timeline.\";s:5:\"title\";s:13:\"Google Mirror\";s:7:\"version\";s:2:\"v1\";s:23:\"x-apiClientRegistration\";O:8:\"stdClass\":1:{s:3:\"url\";s:37:\"https://console.developers.google.com\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:116:\"https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png\";}s:8:\"x-origin\";a:1:{i:0;O:8:\"stdClass\":4:{s:9:\"converter\";O:8:\"stdClass\":2:{s:3:\"url\";s:45:\"https:[...]"
host: www.googleapis.com
basePath: /mirror/v1
paths:
  /accounts/{userToken}/{accountType}/{accountName}:
    post:
      description: Inserts a new account for a user
      operationId: accounts.insert
      tags:
      - accounts
  /contacts:
    get:
      description: Retrieves a list of contacts for the authenticated user.
      operationId: contacts.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - contacts
    post:
      description: Inserts a new contact.
      operationId: contacts.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - contacts
  /contacts/{id}:
    delete:
      description: Deletes a contact.
      operationId: contacts.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - contacts
    get:
      description: Gets a single contact by ID.
      operationId: contacts.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - contacts
    patch:
      description: Updates a contact in place. This method supports patch semantics.
      operationId: contacts.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - contacts
    put:
      description: Updates a contact in place.
      operationId: contacts.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - contacts
  /locations:
    get:
      description: Retrieves a list of locations for the user.
      operationId: locations.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.location
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - locations
  /locations/{id}:
    get:
      description: Gets a single location by ID.
      operationId: locations.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.location
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - locations
  /settings/{id}:
    get:
      description: Gets a single setting by ID.
      operationId: settings.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - settings
  /subscriptions:
    get:
      description: Retrieves a list of subscriptions for the authenticated user and
        service.
      operationId: subscriptions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - subscriptions
    post:
      description: Creates a new subscription.
      operationId: subscriptions.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      description: Deletes a subscription.
      operationId: subscriptions.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - subscriptions
    put:
      description: Updates an existing subscription in place.
      operationId: subscriptions.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - subscriptions
  /timeline:
    get:
      description: Retrieves a list of timeline items for the authenticated user.
      operationId: timeline.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.location
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - timeline
    post:
      description: Inserts a new item into the timeline.
      operationId: timeline.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.location
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - timeline
  /timeline/{id}:
    delete:
      description: Deletes a timeline item.
      operationId: timeline.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.location
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - timeline
    get:
      description: Gets a single timeline item by ID.
      operationId: timeline.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.location
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - timeline
    patch:
      description: Updates a timeline item in place. This method supports patch semantics.
      operationId: timeline.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.location
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - timeline
    put:
      description: Updates a timeline item in place.
      operationId: timeline.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.location
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - timeline
  /timeline/{itemId}/attachments:
    get:
      description: Returns a list of attachments for a timeline item.
      operationId: timeline.attachments.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - timeline
    post:
      description: Adds a new attachment to a timeline item.
      operationId: timeline.attachments.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - timeline
  /timeline/{itemId}/attachments/{attachmentId}:
    delete:
      description: Deletes an attachment from a timeline item.
      operationId: timeline.attachments.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - timeline
    get:
      description: Retrieves an attachment on a timeline item by item ID and attachment
        ID.
      operationId: timeline.attachments.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/glass.timeline
      tags:
      - timeline
schemes:
- https
...
