---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":12:{s:7:\"contact\";O:8:\"stdClass\":2:{s:4:\"name\";s:6:\"Google\";s:3:\"url\";s:18:\"https://google.com\";}s:11:\"description\";s:45:\"Views
  and manages your Google Analytics data.\";s:5:\"title\";s:16:\"Google Analytics\";s:7:\"version\";s:2:\"v3\";s:23:\"x-apiClientRegistration\";O:8:\"stdClass\":1:{s:3:\"url\";s:37:\"https://console.developers.google.com\";}s:21:\"x-apisguru-categories\";a:1:{i:0;s:9:\"analytics\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:109:\"https://api.apis.guru/v2/cache/logo/https_www.gstatic.com_images_icons_material_product_2x_analytics_64dp.png\";}s:8:\"x-origin\";a:1:{i:0;O:8:\"stdClass\":4:{s:9[...]"
host: www.googleapis.com
basePath: /analytics/v3
paths:
  /data/ga:
    get:
      description: Returns Analytics data for a view (profile).
      operationId: data.ga.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - data
  /data/mcf:
    get:
      description: Returns Analytics Multi-Channel Funnels data for a view (profile).
      operationId: data.mcf.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - data
  /data/realtime:
    get:
      description: Returns real time data for a view (profile).
      operationId: data.realtime.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - data
  /management/accountSummaries:
    get:
      description: Lists account summaries (lightweight tree comprised of accounts/properties/profiles)
        to which the user has access.
      operationId: management.accountSummaries.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
  /management/accounts:
    get:
      description: Lists all accounts to which the user has access.
      operationId: management.accounts.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
  /management/accounts/{accountId}/entityUserLinks:
    get:
      description: Lists account-user links for a given account.
      operationId: management.accountUserLinks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users.readonly
      tags:
      - management
    post:
      description: Adds a new user to the given account.
      operationId: management.accountUserLinks.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - management
  /management/accounts/{accountId}/entityUserLinks/{linkId}:
    delete:
      description: Removes a user from the given account.
      operationId: management.accountUserLinks.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - management
    put:
      description: Updates permissions for an existing user on the given account.
      operationId: management.accountUserLinks.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - management
  /management/accounts/{accountId}/filters:
    get:
      description: Lists all filters for an account
      operationId: management.filters.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Create a new filter.
      operationId: management.filters.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/filters/{filterId}:
    delete:
      description: Delete a filter.
      operationId: management.filters.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    get:
      description: Returns a filters to which the user has access.
      operationId: management.filters.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    patch:
      description: Updates an existing filter. This method supports patch semantics.
      operationId: management.filters.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    put:
      description: Updates an existing filter.
      operationId: management.filters.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties:
    get:
      description: Lists web properties to which the user has access.
      operationId: management.webproperties.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Create a new property if the account has fewer than 20 properties.
        Web properties are visible in the Google Analytics interface only if they
        have at least one profile.
      operationId: management.webproperties.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}:
    get:
      description: Gets a web property to which the user has access.
      operationId: management.webproperties.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    patch:
      description: Updates an existing web property. This method supports patch semantics.
      operationId: management.webproperties.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    put:
      description: Updates an existing web property.
      operationId: management.webproperties.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources:
    get:
      description: List custom data sources to which the user has access.
      operationId: management.customDataSources.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/deleteUploadData:
    post:
      description: Delete data associated with a previous upload.
      operationId: management.uploads.deleteUploadData
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads:
    get:
      description: List uploads to which the user has access.
      operationId: management.uploads.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Upload data for a custom data source.
      operationId: management.uploads.uploadData
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads/{uploadId}:
    get:
      description: List uploads to which the user has access.
      operationId: management.uploads.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions:
    get:
      description: Lists custom dimensions to which the user has access.
      operationId: management.customDimensions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Create a new custom dimension.
      operationId: management.customDimensions.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}:
    get:
      description: Get a custom dimension to which the user has access.
      operationId: management.customDimensions.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    patch:
      description: Updates an existing custom dimension. This method supports patch
        semantics.
      operationId: management.customDimensions.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    put:
      description: Updates an existing custom dimension.
      operationId: management.customDimensions.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics:
    get:
      description: Lists custom metrics to which the user has access.
      operationId: management.customMetrics.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Create a new custom metric.
      operationId: management.customMetrics.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}:
    get:
      description: Get a custom metric to which the user has access.
      operationId: management.customMetrics.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    patch:
      description: Updates an existing custom metric. This method supports patch semantics.
      operationId: management.customMetrics.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    put:
      description: Updates an existing custom metric.
      operationId: management.customMetrics.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks:
    get:
      description: Lists webProperty-AdWords links for a given web property.
      operationId: management.webPropertyAdWordsLinks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Creates a webProperty-AdWords link.
      operationId: management.webPropertyAdWordsLinks.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}:
    delete:
      description: Deletes a web property-AdWords link.
      operationId: management.webPropertyAdWordsLinks.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    get:
      description: Returns a web property-AdWords link to which the user has access.
      operationId: management.webPropertyAdWordsLinks.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    patch:
      description: Updates an existing webProperty-AdWords link. This method supports
        patch semantics.
      operationId: management.webPropertyAdWordsLinks.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    put:
      description: Updates an existing webProperty-AdWords link.
      operationId: management.webPropertyAdWordsLinks.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks:
    get:
      description: Lists webProperty-user links for a given web property.
      operationId: management.webpropertyUserLinks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users.readonly
      tags:
      - management
    post:
      description: Adds a new user to the given web property.
      operationId: management.webpropertyUserLinks.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks/{linkId}:
    delete:
      description: Removes a user from the given web property.
      operationId: management.webpropertyUserLinks.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - management
    put:
      description: Updates permissions for an existing user on the given web property.
      operationId: management.webpropertyUserLinks.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles:
    get:
      description: Lists views (profiles) to which the user has access.
      operationId: management.profiles.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Create a new view (profile).
      operationId: management.profiles.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}:
    delete:
      description: Deletes a view (profile).
      operationId: management.profiles.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    get:
      description: Gets a view (profile) to which the user has access.
      operationId: management.profiles.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    patch:
      description: Updates an existing view (profile). This method supports patch
        semantics.
      operationId: management.profiles.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    put:
      description: Updates an existing view (profile).
      operationId: management.profiles.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks:
    get:
      description: Lists profile-user links for a given view (profile).
      operationId: management.profileUserLinks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users.readonly
      tags:
      - management
    post:
      description: Adds a new user to the given view (profile).
      operationId: management.profileUserLinks.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks/{linkId}:
    delete:
      description: Removes a user from the given view (profile).
      operationId: management.profileUserLinks.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - management
    put:
      description: Updates permissions for an existing user on the given view (profile).
      operationId: management.profileUserLinks.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.manage.users
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments:
    get:
      description: Lists experiments to which the user has access.
      operationId: management.experiments.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Create a new experiment.
      operationId: management.experiments.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}:
    delete:
      description: Delete an experiment.
      operationId: management.experiments.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    get:
      description: Returns an experiment to which the user has access.
      operationId: management.experiments.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    patch:
      description: Update an existing experiment. This method supports patch semantics.
      operationId: management.experiments.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    put:
      description: Update an existing experiment.
      operationId: management.experiments.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals:
    get:
      description: Lists goals to which the user has access.
      operationId: management.goals.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Create a new goal.
      operationId: management.goals.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}:
    get:
      description: Gets a goal to which the user has access.
      operationId: management.goals.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    patch:
      description: Updates an existing goal. This method supports patch semantics.
      operationId: management.goals.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    put:
      description: Updates an existing goal.
      operationId: management.goals.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks:
    get:
      description: Lists all profile filter links for a profile.
      operationId: management.profileFilterLinks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Create a new profile filter link.
      operationId: management.profileFilterLinks.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}:
    delete:
      description: Delete a profile filter link.
      operationId: management.profileFilterLinks.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    get:
      description: Returns a single profile filter link.
      operationId: management.profileFilterLinks.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    patch:
      description: Update an existing profile filter link. This method supports patch
        semantics.
      operationId: management.profileFilterLinks.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    put:
      description: Update an existing profile filter link.
      operationId: management.profileFilterLinks.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports:
    get:
      description: Lists unsampled reports to which the user has access.
      operationId: management.unsampledReports.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Create a new unsampled report.
      operationId: management.unsampledReports.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports/{unsampledReportId}:
    delete:
      description: Deletes an unsampled report.
      operationId: management.unsampledReports.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    get:
      description: Returns a single unsampled report.
      operationId: management.unsampledReports.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences:
    get:
      description: Lists remarketing audiences to which the user has access.
      operationId: management.remarketingAudience.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    post:
      description: Creates a new remarketing audience.
      operationId: management.remarketingAudience.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}:
    delete:
      description: Delete a remarketing audience.
      operationId: management.remarketingAudience.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    get:
      description: Gets a remarketing audience to which the user has access.
      operationId: management.remarketingAudience.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
    patch:
      description: Updates an existing remarketing audience. This method supports
        patch semantics.
      operationId: management.remarketingAudience.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
    put:
      description: Updates an existing remarketing audience.
      operationId: management.remarketingAudience.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      tags:
      - management
  /management/segments:
    get:
      description: Lists segments to which the user has access.
      operationId: management.segments.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - management
  /metadata/{reportType}/columns:
    get:
      description: Lists all columns for a report type
      operationId: metadata.columns.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.edit
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.readonly
      tags:
      - metadata
  /provisioning/createAccountTicket:
    post:
      description: Creates an account ticket.
      operationId: provisioning.createAccountTicket
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.provision
      tags:
      - provisioning
  /provisioning/createAccountTree:
    post:
      description: Provision account.
      operationId: provisioning.createAccountTree
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.provision
      tags:
      - provisioning
  /userDeletion/userDeletionRequests:upsert:
    post:
      description: Insert or update a user deletion requests.
      operationId: userDeletion.userDeletionRequest.upsert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/analytics.user.deletion
      tags:
      - userDeletion
schemes:
- https
...
