---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":12:{s:7:\"contact\";O:8:\"stdClass\":2:{s:4:\"name\";s:6:\"Google\";s:3:\"url\";s:18:\"https://google.com\";}s:11:\"description\";s:45:\"Accesses
  Tag Manager accounts and containers.\";s:5:\"title\";s:11:\"Tag Manager\";s:7:\"version\";s:2:\"v1\";s:23:\"x-apiClientRegistration\";O:8:\"stdClass\":1:{s:3:\"url\";s:37:\"https://console.developers.google.com\";}s:21:\"x-apisguru-categories\";a:1:{i:0;s:9:\"analytics\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:116:\"https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png\";}s:8:\"x-origin\";a:1:{i:0;O:8:\"stdClass\":4:{s:9:[...]"
host: www.googleapis.com
basePath: /tagmanager/v1
paths:
  /accounts:
    get:
      description: Lists all GTM Accounts that a user has access to.
      operationId: accounts.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.accounts
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
  /accounts/{accountId}:
    get:
      description: Gets a GTM Account.
      operationId: accounts.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.accounts
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    put:
      description: Updates a GTM Account.
      operationId: accounts.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.accounts
      tags:
      - accounts
  /accounts/{accountId}/containers:
    get:
      description: Lists all Containers that belongs to a GTM Account.
      operationId: accounts.containers.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    post:
      description: Creates a Container.
      operationId: accounts.containers.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}:
    delete:
      description: Deletes a Container.
      operationId: accounts.containers.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.delete.containers
      tags:
      - accounts
    get:
      description: Gets a Container.
      operationId: accounts.containers.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    put:
      description: Updates a Container.
      operationId: accounts.containers.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/environments:
    get:
      description: Lists all GTM Environments of a GTM Container.
      operationId: accounts.containers.environments.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    post:
      description: Creates a GTM Environment.
      operationId: accounts.containers.environments.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/environments/{environmentId}:
    delete:
      description: Deletes a GTM Environment.
      operationId: accounts.containers.environments.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
    get:
      description: Gets a GTM Environment.
      operationId: accounts.containers.environments.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    patch:
      description: Updates a GTM Environment. This method supports patch semantics.
      operationId: accounts.containers.environments.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
    put:
      description: Updates a GTM Environment.
      operationId: accounts.containers.environments.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/folders:
    get:
      description: Lists all GTM Folders of a Container.
      operationId: accounts.containers.folders.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    post:
      description: Creates a GTM Folder.
      operationId: accounts.containers.folders.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/folders/{folderId}:
    delete:
      description: Deletes a GTM Folder.
      operationId: accounts.containers.folders.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
    get:
      description: Gets a GTM Folder.
      operationId: accounts.containers.folders.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    put:
      description: Updates a GTM Folder.
      operationId: accounts.containers.folders.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/folders/{folderId}/entities:
    get:
      description: List all entities in a GTM Folder.
      operationId: accounts.containers.folders.entities.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/move_folders/{folderId}:
    put:
      description: Moves entities to a GTM Folder.
      operationId: accounts.containers.move_folders.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/reauthorize_environments/{environmentId}:
    put:
      description: Re-generates the authorization code for a GTM Environment.
      operationId: accounts.containers.reauthorize_environments.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.publish
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/tags:
    get:
      description: Lists all GTM Tags of a Container.
      operationId: accounts.containers.tags.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    post:
      description: Creates a GTM Tag.
      operationId: accounts.containers.tags.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/tags/{tagId}:
    delete:
      description: Deletes a GTM Tag.
      operationId: accounts.containers.tags.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
    get:
      description: Gets a GTM Tag.
      operationId: accounts.containers.tags.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    put:
      description: Updates a GTM Tag.
      operationId: accounts.containers.tags.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/triggers:
    get:
      description: Lists all GTM Triggers of a Container.
      operationId: accounts.containers.triggers.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    post:
      description: Creates a GTM Trigger.
      operationId: accounts.containers.triggers.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/triggers/{triggerId}:
    delete:
      description: Deletes a GTM Trigger.
      operationId: accounts.containers.triggers.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
    get:
      description: Gets a GTM Trigger.
      operationId: accounts.containers.triggers.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    put:
      description: Updates a GTM Trigger.
      operationId: accounts.containers.triggers.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/variables:
    get:
      description: Lists all GTM Variables of a Container.
      operationId: accounts.containers.variables.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    post:
      description: Creates a GTM Variable.
      operationId: accounts.containers.variables.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/variables/{variableId}:
    delete:
      description: Deletes a GTM Variable.
      operationId: accounts.containers.variables.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
    get:
      description: Gets a GTM Variable.
      operationId: accounts.containers.variables.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    put:
      description: Updates a GTM Variable.
      operationId: accounts.containers.variables.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/versions:
    get:
      description: Lists all Container Versions of a GTM Container.
      operationId: accounts.containers.versions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    post:
      description: Creates a Container Version.
      operationId: accounts.containers.versions.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}:
    delete:
      description: Deletes a Container Version.
      operationId: accounts.containers.versions.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      tags:
      - accounts
    get:
      description: Gets a Container Version.
      operationId: accounts.containers.versions.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.readonly
      tags:
      - accounts
    put:
      description: Updates a Container Version.
      operationId: accounts.containers.versions.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/publish:
    post:
      description: Publishes a Container Version.
      operationId: accounts.containers.versions.publish
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.publish
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/restore:
    post:
      description: Restores a Container Version. This will overwrite the container's
        current configuration (including its variables, triggers and tags). The operation
        will not have any effect on the version that is being served (i.e. the published
        version).
      operationId: accounts.containers.versions.restore
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containers
      tags:
      - accounts
  /accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/undelete:
    post:
      description: Undeletes a Container Version.
      operationId: accounts.containers.versions.undelete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.edit.containerversions
      tags:
      - accounts
  /accounts/{accountId}/permissions:
    get:
      description: List all users that have access to the account along with Account
        and Container Permissions granted to each of them.
      operationId: accounts.permissions.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
    post:
      description: Creates a user's Account & Container Permissions.
      operationId: accounts.permissions.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
  /accounts/{accountId}/permissions/{permissionId}:
    delete:
      description: Removes a user from the account, revoking access to it and all
        of its containers.
      operationId: accounts.permissions.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
    get:
      description: Gets a user's Account & Container Permissions.
      operationId: accounts.permissions.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
    put:
      description: Updates a user's Account & Container Permissions.
      operationId: accounts.permissions.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/tagmanager.manage.users
      tags:
      - accounts
schemes:
- https
...
