---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":14:{s:7:\"contact\";O:8:\"stdClass\":2:{s:4:\"name\";s:6:\"Google\";s:3:\"url\";s:18:\"https://google.com\";}s:11:\"description\";s:55:\"Accesses
  a Google App Engine Pull Task Queue over REST.\";s:7:\"license\";O:8:\"stdClass\":2:{s:4:\"name\";s:32:\"Creative
  Commons Attribution 3.0\";s:3:\"url\";s:43:\"http://creativecommons.org/licenses/by/3.0/\";}s:14:\"termsOfService\";s:36:\"https://developers.google.com/terms/\";s:5:\"title\";s:9:\"TaskQueue\";s:7:\"version\";s:7:\"v1beta2\";s:23:\"x-apiClientRegistration\";O:8:\"stdClass\":1:{s:3:\"url\";s:37:\"https://console.developers.google.com\";}s:21:\"x-apisguru-categories\";a:1:{i:0;s:7:\"backend\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:116:\"https://api.apis.guru/v2/cache/logo/https_www.g[...]"
host: www.googleapis.com
basePath: /taskqueue/v1beta2/projects
paths:
  /{project}/taskqueues/{taskqueue}:
    get:
      description: Get detailed information about a TaskQueue.
      operationId: taskqueues.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue.consumer
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue.consumer
      tags:
      - taskqueues
  /{project}/taskqueues/{taskqueue}/tasks:
    get:
      description: List Tasks in a TaskQueue
      operationId: tasks.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue.consumer
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue.consumer
      tags:
      - tasks
    post:
      description: Insert a new task in a TaskQueue
      operationId: tasks.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue.consumer
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue.consumer
      tags:
      - tasks
  /{project}/taskqueues/{taskqueue}/tasks/lease:
    post:
      description: Lease 1 or more tasks from a TaskQueue.
      operationId: tasks.lease
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue.consumer
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue.consumer
      tags:
      - tasks
  /{project}/taskqueues/{taskqueue}/tasks/{task}:
    delete:
      description: Delete a task from a TaskQueue.
      operationId: tasks.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue.consumer
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue.consumer
      tags:
      - tasks
    get:
      description: Get a particular task from a TaskQueue.
      operationId: tasks.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue.consumer
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue.consumer
      tags:
      - tasks
    patch:
      description: Update tasks that are leased out of a TaskQueue. This method supports
        patch semantics.
      operationId: tasks.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue.consumer
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue.consumer
      tags:
      - tasks
    post:
      description: Update tasks that are leased out of a TaskQueue.
      operationId: tasks.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue
      - Oauth2:
        - https://www.googleapis.com/auth/taskqueue.consumer
        Oauth2c:
        - https://www.googleapis.com/auth/taskqueue.consumer
      tags:
      - tasks
schemes:
- https
...
