---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":12:{s:7:\"contact\";O:8:\"stdClass\":3:{s:4:\"name\";s:6:\"Google\";s:3:\"url\";s:18:\"https://google.com\";s:9:\"x-twitter\";s:7:\"youtube\";}s:11:\"description\";s:38:\"Retrieves
  your YouTube Analytics data.\";s:5:\"title\";s:17:\"YouTube Analytics\";s:7:\"version\";s:2:\"v1\";s:23:\"x-apiClientRegistration\";O:8:\"stdClass\":1:{s:3:\"url\";s:37:\"https://console.developers.google.com\";}s:21:\"x-apisguru-categories\";a:2:{i:0;s:9:\"analytics\";i:1;s:5:\"media\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:126:\"https://api.apis.guru/v2/cache/logo/https_upload.wikimedia.org_wikipedia_commons_e_e1_YouTube_play_buttom_icon_(2013-2017).svg\";}s:8:\"x-origin\";a:1:{i:[...]"
host: www.googleapis.com
basePath: /youtube/analytics/v1
paths:
  /groupItems:
    delete:
      description: Removes an item from a group.
      operationId: groupItems.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/youtube
      - Oauth2:
        - https://www.googleapis.com/auth/youtubepartner
      tags:
      - groupItems
    get:
      description: Returns a collection of group items that match the API request
        parameters.
      operationId: groupItems.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/youtube
      - Oauth2:
        - https://www.googleapis.com/auth/youtube.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/youtubepartner
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - groupItems
    post:
      description: Creates a group item.
      operationId: groupItems.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/youtube
      - Oauth2:
        - https://www.googleapis.com/auth/youtubepartner
      tags:
      - groupItems
  /groups:
    delete:
      description: Deletes a group.
      operationId: groups.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/youtube
      - Oauth2:
        - https://www.googleapis.com/auth/youtubepartner
      tags:
      - groups
    get:
      description: Returns a collection of groups that match the API request parameters.
        For example, you can retrieve all groups that the authenticated user owns,
        or you can retrieve one or more groups by their unique IDs.
      operationId: groups.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/youtube
      - Oauth2:
        - https://www.googleapis.com/auth/youtube.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/youtubepartner
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - groups
    post:
      description: Creates a group.
      operationId: groups.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/youtube
      - Oauth2:
        - https://www.googleapis.com/auth/youtubepartner
      tags:
      - groups
    put:
      description: Modifies a group. For example, you could change a group's title.
      operationId: groups.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/youtube
      - Oauth2:
        - https://www.googleapis.com/auth/youtubepartner
      tags:
      - groups
  /reports:
    get:
      description: Retrieve your YouTube Analytics reports.
      operationId: reports.query
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/youtube
      - Oauth2:
        - https://www.googleapis.com/auth/youtube.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - reports
schemes:
- https
...
