---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":5:{s:5:\"title\";s:21:\"NPR One API Reference\";s:11:\"description\";s:452:\"NPR
  One is a smart application that brings the best of NPR and Member Station programming,
  newscasts,\npodcasts, and stories together to create a new experience for listening.
  It provides an editor-curated and\nlocalized mobile listening experience based on
  the content the listener chooses, likes, shares, and enjoys.\nThe API provides all
  of the content and customization in a simple, structured way that is easy for application\ndevelopers
  to implement.\";s:14:\"termsOfService\";s:39:\"http://dev.npr.org/develop/terms-of-use\";s:7:\"contact\";O:8:\"stdClass\":3:{s:4:\"name\";s:23:\"NPR
  One Enterprise Team\";s:3:\"url\";s:18:\"http://dev.npr.org\";s:5:\"email\";s:24:\"NPROneEnterprise@npr.org\";}s:7:\"version\";s:9:\"Beryllium\";}"
host: api.npr.org
paths:
  /authorization/v2/token:
    post:
      tags:
      - authorization
      summary: Create a new OAuth2 access token
      description: Please be aware that the required parameters are contingent on
        the `grant_type` that you select.nnFor the `authorization_code` grant type,
        you are **required** to pass in the `code` and `redirect_uri` parameters.
        `service`, `username` and `password` parameters will be ignored.nnFor the
        `client_credentials` grant type, you do not need to pass in any additional
        parameters beyond the basic requirements. `code`, `redirect_uri`, `service`,
        `username` and `password` parameters will be ignored.nnFor the `device_code`
        grant type, you are **required** to pass in the `code` parameter. `redirect_uri`,
        `service`, `username` and `password` parameters will be ignored.nnFor the
        `password` grant type, you are **required** to pass in the `username` and
        `password` parameters. If you are logging in via a social service, you should
        also pass in the `service` parameter. (In this case, the access token you
        receive from the social service will serve as both your username and password.)
        The `code` and `redirect_uri` parameters are ignored.nThird-party developers
        do not have access to this grant type.nnThe `temporary_user` grant type is
        a custom grant type created by NPR to suit our needs for functionality such
        as our &quot;try-before-you-buy&quot; experience. If you are a third-party
        developer, you will not have access to this grant type unless we have explicitly
        given you permission within our system.nFor this grant type, you do not need
        to pass in any additional parameters beyond the basic requirements. `code`,
        `redirect_uri`, `service`, `username` and `password` parameters will be ignored.nnIf
        you are unsure of which grant type to select, assume that `authorization_code`
        is the one you want.
      operationId: createToken
  /authorization/v2/authorize:
    get:
      tags:
      - authorization
      summary: Show a web-based login/signup form to a user
      description: If the parameters passed to this endpoint are correct, it will
        redirect to `npr.org/oauth2/login` for the user to complete the sign-in.nnCurrently
        acceptable values for `scope` are any combination of the following:n- `identity.readonly`
        - for read-only access to the Identity Servicen- `identity.write` - for write
        access to the Identity Servicen- `listening.readonly` - for read-only access
        to the Listening Servicen- `listening.write` - for write access to the Listening
        Servicen- `localactivation` - for all access to the Local Activation ServicenIt
        is generally suggested that you assume that you will need all of the current
        scopes in order to successfully implement an NPR One application.nnIf the
        parameters passed in are NOT correct and the client passed in a valid `redirect_uri`
        parameter, the request will be redirected to `{{YOUR_REDIRECT_URI}}?error={{ERROR_TYPE}}&message={{ERROR_DESCRIPTION}}`.nIf
        the parameters passed are NOT correct and the client did not pass in a valid
        `redirect_uri` parameter, this endpoint will return the errors encoded as
        JSON objects (along with the corresponding HTTP status code -- usually 400).nThe
        latter is intended for development and debugging purposes -- in a real-world
        situation, errors returned as JSON objects are irretrievable by the client
        application, and thus passing in a valid `redirect_uri` is critical even for
        the purpose of capturing errors.nnIf the user successfully logs in and authorizes
        the application, the request will be redirected to `{{YOUR_REDIRECT_URI}}?code={{AUTHORIZATION_CODE}}&state={{CSRF_TOKEN}}`nnIf
        the user DENIES the application, they will be redirected to `{{YOUR_REDIRECT_URI}}?error=denied&message=The%20user%20has%20denied%20the%20login%20and%20access%20request&state={{CSRF_TOKEN}}`.nThis
        means that if your application flow requires a user to log in in order to
        proceed, it is up to you to give them the proper messaging explaining that
        the sign-in must be authorized in order to continue.nnFinally, please do not
        confuse an authorization code with an access token. Once your app has completed
        this flow, you will still need to call `POST /authorization/v2/token` in order
        to swap the code for a valid access token.
      operationId: getAuthorizationPage
  /authorization/v2/device:
    post:
      tags:
      - authorization
      summary: Initiate an OAuth2 login flow for limited input devices
      description: This flow should only be used by clients who cannot show a native
        webview or do not have advanced input controls. It is an alternative to `GET
        /authorization/v2/authorize`.nnThird-party clients will need to use one or
        the other of these two endpoints, but they will generally not use both.
      operationId: generateDeviceCode
  /authorization/v2/token/revoke:
    post:
      tags:
      - authorization
      summary: Revokes an existing OAuth2 access token
      description: Our implementation follows the proposed IETF specification [RFC-7009](https://tools.ietf.org/html/rfc7009).nnIf
        your client application offers the ability to for a logged-in user to log
        out, and you have access to a long-livedn`client_credentials` token (i.e.
        you have generated one that you are storing securely for the lifetime of the
        entire appninstall), we suggest (but do not require) that you call this endpoint
        and revoke the access token belonging to thenlogged-in user as part of your
        logout process. If you do not already have a long-lived `client_credentials`
        token,nplease don't generate one just for the purposes of calling this endpoint.nnIf
        you are building a prototype application, we also recommend that you use this
        endpoint to clean up access tokensnthat you generate during the testing of
        your app and do not intend to reuse.
      operationId: revokeToken
  /identity/v2/user:
    get:
      tags:
      - identity
      summary: Get the latest state information about the logged-in user
      description: After a successful login, the client should send a `GET` call approximately
        once an hour to refresh the user data.
      operationId: getUser
      security:
      - oauth2:
        - identity.readonly
  /identity/v2/stations:
    put:
      tags:
      - identity
      summary: Update the logged-in user's favorite station(s)
      description: Right now, only the primary station can be changed. Previously
        selected stations will not be deleted, but the new station will be moved to
        first in the array.
      operationId: updateStations
      security:
      - oauth2:
        - identity.write
  /identity/v2/user/inherit:
    post:
      tags:
      - identity
      summary: Copy listening data from a temporary user account to the logged-in
        user's account
      description: This can and should only be used by clients who have access to
        the `temporary_user` grant type.nThird-party developers do not have access
        to this grant type by default, and will not need this endpoint.
      operationId: inheritFromTempUser
      security:
      - oauth2:
        - identity.write
  /identity/v2/following:
    post:
      tags:
      - identity
      summary: Update the following status of the logged-in user for a particular
        aggregation
      description: After a successful call, this returns a User document with an updated
        list of affiliations.
      operationId: postFollowing
      security:
      - oauth2:
        - identity.write
  /listening/v2/channels:
    get:
      tags:
      - listening
      summary: Get the list of available channels
      description: These channels allow the user to specify a focus for the content
        returned in the recommendations endpoint.
      operationId: getChannels
      security:
      - oauth2:
        - listening.readonly
  /listening/v2/ratings:
    post:
      tags:
      - listening
      summary: Collect new ratings for media previously recommended to the logged-in
        user
      description: This endpoint is the main mechanism for providing feedback from
        the user to NPR about the recommendations that are obtained from `GET /listening/v2/recommendations`.nnA
        fully-populated link to this endpoint is returned with each individual recommendation
        and is located in the AudioItemDocument under the `links['recommendations']`
        object. The query parameters in this link should not be modified.nBe sure
        to copy and send back the entire ratings object (RatingData), as new fields
        may be added to it in the future.nnThis endpoint can return a blank JSON.doc
        or AudioItemDocument depending on the `recommend=true|false` parameter. The
        `recommend=true` flag allows this endpoint to both receive ratings and send
        back recommendations in the same call.
      operationId: postRating
      security:
      - oauth2:
        - listening.write
  /listening/v2/recommendations:
    get:
      tags:
      - listening
      summary: Get a list of media for the logged-in user from NPR's recommendation
        engine
      description: This endpoint returns a list of audio recommendations. It is designed
        to be used for an initial list of recommendations, and then `GET /listening/v2/ratings?recommend=true`
        should be used for subsequent requests for recommendations.nnA fully-populated
        link to the ratings endpoint is returned with each individual recommendation
        and is located in the AudioItemDocument under the `links['recommendations']`
        object. The query parameters in this link should not be modified.nBe sure
        to copy and send back the entire ratings object (RatingData), as new fields
        may be added to it in the future.
      operationId: getRecommendations
      security:
      - oauth2:
        - listening.readonly
  /listening/v2/history:
    get:
      tags:
      - listening
      summary: Get recent ratings the logged-in user has submitted
      description: This endpoint provides the list of recently-rated audio recommendations
        that the logged-in user has consumed. Some rated recommendations are filtered,
        such as sponsorship and donation.
      operationId: getHistory
      security:
      - oauth2:
        - listening.readonly
  /listening/v2/aggregation/{aggId}/recommendations:
    get:
      tags:
      - listening
      summary: Get a set of recommendations for an aggregation
      description: This endpoint provides a list of recent audio items associated
        with the aggregation along with metadata about the aggregation.
      operationId: getAggRecommendations
      security:
      - oauth2:
        - listening.readonly
  /listening/v2/search/recommendations:
    get:
      tags:
      - listening
      summary: Get a list of recent audio and aggregation items associated with search
        terms
      description: In the schema shown below, SearchItemDocument is not an actual
        type of returned object; the object returned by a search will be either an
        AggregationAudioItemListDocument or an AudioItemDocument.
      operationId: getSearchRecommendations
      security:
      - oauth2:
        - listening.readonly
  /localactivation/v2/donate_email:
    get:
      tags:
      - localactivation
      summary: Send a donation email to the logged-in user (only on request)
      description: This will send a station-specific donation email to the logged-in
        user.
      operationId: sendDonationEmail
      security:
      - oauth2:
        - localactivation
  /sponsorship/v2/ads:
    get:
      tags:
      - sponsorship
      summary: Request DAAST sponsorship units
      description: '**Not** for use by NPR One clients (for whom sponsorship is already
        integrated into the Listening Service), this endpoint is designed to be used
        by our other client applications to request sponsorship on behalf of a user.
        Sponsorship units are returned in the form of DAAST XML. It is worth noting
        that this endpoint attempts to always return XML, even in the case of exceptions.nnThe
        default behavior of this endpoint is asynchronous; on an initial request,
        a call to our external sponsorship provider is placed on a queue, which is
        typically processed within 3 minutes. Once the sponsorship call is received
        and processed, the returned sponsorship units are placed in a cache on our
        server for the current user. Subsequent calls to this endpoint will return
        DAAST sponsorship units from this cache until tracking information is submitted,
        which removes the ad from the cache and will automatically request additional
        ads asynchronously if there are fewer than a certain number remaining in the
        cache.nnFor development purposes, it''s worth noting that there is currently
        no way to clear a user''s cache without submitting some form of tracking.'
      operationId: getAds
    post:
      tags:
      - sponsorship
      summary: Record tracking data for DAAST sponsorship units
      description: '**Not** for use by NPR One clients (for whom sponsorship is already
        integrated into the Listening Service), this endpoint is designed to be used
        by our other client applications to submit tracking information for sponsorship
        units obtained from the `GET /sponsorship/v2/ads` endpoint.nnThe tracking
        information should be submitted in the body of the request in the form of
        a JSON object following the Collection.Doc+JSON specification.'
      operationId: receiveAdTracking
schemes:
- https
...
