---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":12:{s:7:\"contact\";O:8:\"stdClass\":2:{s:4:\"name\";s:6:\"Google\";s:3:\"url\";s:18:\"https://google.com\";}s:11:\"description\";s:60:\"An
  API for creating and editing Google Slides presentations.\";s:5:\"title\";s:13:\"Google
  Slides\";s:7:\"version\";s:2:\"v1\";s:23:\"x-apiClientRegistration\";O:8:\"stdClass\":1:{s:3:\"url\";s:37:\"https://console.developers.google.com\";}s:21:\"x-apisguru-categories\";a:1:{i:0;s:5:\"cloud\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:116:\"https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png\";}s:8:\"x-origin\";a:1:{i:0;O:8:\"stdClass\":4:{s:9:\"converter\";O:8:\"stdClass\":2:{s:3:\"url\";s:45:\"https://github.c[...]"
host: slides.googleapis.com
basePath: /
paths:
  /v1/presentations:
    post:
      description: Creates a new presentation using the title given in the request.
        If anpresentationId is provided, uses it as the ID of the new presentation.nOtherwise,
        a new presentationId is generated.nReturns the created presentation.
      operationId: presentations.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/presentations
      tags:
      - presentations
  /v1/presentations/{presentationId}:
    get:
      description: Gets the latest version of the specified presentation.
      operationId: presentations.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/presentations
      - Oauth2:
        - https://www.googleapis.com/auth/presentations.readonly
      tags:
      - presentations
  /v1/presentations/{presentationId}/pages/{pageObjectId}:
    get:
      description: Gets the latest version of the specified page in the presentation.
      operationId: presentations.pages.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/presentations
      - Oauth2:
        - https://www.googleapis.com/auth/presentations.readonly
      tags:
      - presentations
  /v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail:
    get:
      description: Generates a thumbnail of the latest version of the specified page
        in thenpresentation and returns a URL to the thumbnail image.nnThis request
        counts as an [expensive read request](/slides/limits) fornquota purposes.
      operationId: presentations.pages.getThumbnail
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/presentations
      - Oauth2:
        - https://www.googleapis.com/auth/presentations.readonly
      tags:
      - presentations
  /v1/presentations/{presentationId}:batchUpdate:
    post:
      description: 'Applies one or more updates to the presentation.nnEach request
        is validated beforenbeing applied. If any request is not valid, then the entire
        request willnfail and nothing will be applied.nnSome requests have replies
        tongive you some information about how they are applied. Other requests donnot
        need to return information; these each return an empty reply.nThe order of
        replies matches that of the requests.nnFor example, suppose you call batchUpdate
        with four updates, and only thenthird one returns information. The response
        would have two empty replies:nthe reply to the third request, and another
        empty reply, in that order.nnBecause other users may be editing the presentation,
        the presentationnmight not exactly reflect your changes: your changes maynbe
        altered with respect to collaborator changes. If there are noncollaborators,
        the presentation should reflect your changes. In any case,nthe updates in
        your request are guaranteed to be applied togethernatomically.'
      operationId: presentations.batchUpdate
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/drive
      - Oauth2:
        - https://www.googleapis.com/auth/drive.file
      - Oauth2:
        - https://www.googleapis.com/auth/drive.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/presentations
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets
      - Oauth2:
        - https://www.googleapis.com/auth/spreadsheets.readonly
      tags:
      - presentations
schemes:
- https
...
