---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":10:{s:7:\"contact\";O:8:\"stdClass\":2:{s:4:\"name\";s:6:\"Google\";s:3:\"url\";s:18:\"https://google.com\";}s:11:\"description\";s:135:\"Schedules
  reporting jobs containing your YouTube Analytics data and downloads the resulting
  bulk data reports in the form of CSV files.\";s:5:\"title\";s:17:\"YouTube Reporting\";s:7:\"version\";s:2:\"v1\";s:23:\"x-apiClientRegistration\";O:8:\"stdClass\":1:{s:3:\"url\";s:37:\"https://console.developers.google.com\";}s:6:\"x-logo\";O:8:\"stdClass\":1:{s:3:\"url\";s:116:\"https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png\";}s:8:\"x-origin\";O:8:\"stdClass\":3:{s:6:\"format\";s:6:\"google\";s:3:\"url\";s:69:\"https://ww[...]"
host: youtubereporting.googleapis.com
basePath: /
paths:
  /v1/jobs:
    get:
      description: Lists jobs.
      operationId: youtubereporting.jobs.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
    post:
      description: Creates a job and returns it.
      operationId: youtubereporting.jobs.create
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
  /v1/jobs/{jobId}:
    delete:
      description: Deletes a job.
      operationId: youtubereporting.jobs.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
    get:
      description: Gets a job.
      operationId: youtubereporting.jobs.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
  /v1/jobs/{jobId}/reports:
    get:
      description: Lists reports created by a specific job. Returns NOT_FOUND if the
        job does not exist.
      operationId: youtubereporting.jobs.reports.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
  /v1/jobs/{jobId}/reports/{reportId}:
    get:
      description: Gets the metadata of a specific report.
      operationId: youtubereporting.jobs.reports.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - jobs
  /v1/media/{resourceName}:
    get:
      description: Method for media download. Download is supported on the URI `/v1/media/{+name}?alt=media`.
      operationId: youtubereporting.media.download
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - media
  /v1/reportTypes:
    get:
      description: Lists report types.
      operationId: youtubereporting.reportTypes.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics-monetary.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/yt-analytics.readonly
      tags:
      - reportTypes
schemes:
- https
...
