---
swagger: "2.0"
info: !php/object "O:8:\"stdClass\":6:{s:11:\"description\";s:274:\"This is a sample
  server goodchar server.  You can find out more about Swagger at [http://goodchar.io](http://goodchar.io)
  or on [irc.freenode.net, #goodchar](http://goodchar.io/irc/).  For this sample,
  you can use the api key `special-key` to test the authorization filters.\";s:7:\"version\";s:5:\"1.0.0\";s:5:\"title\";s:8:\"GoodChar\";s:14:\"termsOfService\";s:25:\"http://goodchar.io/terms/\";s:7:\"contact\";O:8:\"stdClass\":1:{s:5:\"email\";s:19:\"apiteam@goodchar.io\";}s:7:\"license\";O:8:\"stdClass\":2:{s:4:\"name\";s:10:\"Apache
  2.0\";s:3:\"url\";s:47:\"http://www.apache.org/licenses/LICENSE-2.0.html\";}}"
host: gc.goodchar.io
basePath: /gc
paths:
  /ngo/allocateVolunteer:
    post:
      tags:
      - ngo
      summary: Add a new Volunteer to the Organization
      description: ""
      operationId: allocateVolunteer
      security:
      - ngo_auth:
        - write:ngo
        - read:ngo
  /ngo/createDonationCamp:
    post:
      tags:
      - ngo
      summary: Create a new donation camp for distribution
      description: ""
      operationId: createDonationCamp
      security:
      - ngo_auth:
        - write:ngo
        - read:ngo
  /ngo/validateVolunteers:
    put:
      tags:
      - ngo
      summary: Update an existing Volunteer
      description: ""
      operationId: validateVolunteers
      security:
      - ngo_auth:
        - write:ngo
        - read:ngo
  /ngo/allocateAssetsToVolunteer:
    put:
      tags:
      - ngo
      summary: Allocate Asset to volunteer
      description: ""
      operationId: allocateAssetsToVolunteer
      security:
      - ngo_auth:
        - write:ngo
        - read:ngo
  /ngo/allocateLogistics:
    post:
      tags:
      - ngo
      summary: allocate logistics to donation
      description: ""
      operationId: allocateLogistics
      security:
      - ngo_auth:
        - write:ngo
        - read:ngo
  /ngo/listProject:
    get:
      tags:
      - ngo
      summary: Finds projects listed in org
      description: Multiple projects lists
      operationId: listProject
      security:
      - ngo_auth:
        - write:ngo
        - read:ngo
  /ngo/listCauses:
    get:
      tags:
      - ngo
      summary: Finds Causes listed in org
      description: Multiple Causes lists
      operationId: listCauses
      security:
      - ngo_auth:
        - write:ngo
        - read:ngo
  /volunteer/registerSelf:
    post:
      tags:
      - Volunteer
      summary: register as new volunteer
      description: ""
      operationId: VolunteerregisterSelf
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /volunteer/pickupAssetLot:
    post:
      tags:
      - Volunteer
      summary: pick asset & assign lot
      description: ""
      operationId: pickupAssetLot
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /volunteer/startDonationCamp:
    put:
      tags:
      - Volunteer
      summary: Start donation camp
      description: ""
      operationId: startDonationCamp
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /volunteer/closeDonationCamp:
    put:
      tags:
      - Volunteer
      summary: close donation camp
      description: ""
      operationId: closeDonationCamp
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /volunteer/scanAssetForDonee:
    put:
      tags:
      - Volunteer
      summary: scan asset to distribute to donee
      description: ""
      operationId: scanAssetForDonee
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /volunteer/registerDonee:
    post:
      tags:
      - Volunteer
      summary: register as new donee
      description: ""
      operationId: registerDoneeByVolunteer
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /volunteer/scanDoneeFingerPrint:
    post:
      tags:
      - Volunteer
      summary: scan donee biometric
      description: ""
      operationId: scanDoneeFingerPrint
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /volunteer/playAudio:
    get:
      tags:
      - Volunteer
      summary: Play audio in distribution process
      description: ""
      operationId: playAudio
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /Donor/registerSelf:
    post:
      tags:
      - Donor
      summary: register as new Donor
      description: ""
      operationId: DonorregisterSelf
      security:
      - donor_auth:
        - write:donor
        - read:donor
  /Donor/donateAsset:
    put:
      tags:
      - Donor
      summary: donate Asset to ngo
      description: ""
      operationId: donateAsset
      security:
      - donor_auth:
        - write:donor
        - read:donor
  /Donee/registerDonee:
    post:
      tags:
      - Donee
      summary: register Donee details
      description: ""
      operationId: registerDonee
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /Donee/requestHelp:
    post:
      tags:
      - Donee
      summary: request Help
      description: ""
      operationId: requestHelp
      security:
      - donee_auth:
        - write:donee
        - read:donee
  /Donation/retrieveDonation:
    get:
      tags:
      - Donation
      summary: List donation
      description: Display donation details
      operationId: retrieveDonation
      security:
      - donor_auth:
        - write:donor
        - read:donor
  /Transactions/createTransaction:
    put:
      tags:
      - Transactions
      summary: Start transation
      description: ""
      operationId: createTransaction
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /Transactions/retriveTransaction:
    get:
      tags:
      - Transactions
      summary: List transactions
      description: Display transaction details
      operationId: retriveTransaction
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /Asset/registerAsset:
    post:
      tags:
      - Asset
      summary: Create a new Asset
      description: ""
      operationId: registerAsset
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /Asset/assciateAssetToLot:
    put:
      tags:
      - ngo
      summary: associate Asset with lot number
      description: ""
      operationId: assciateAssetToLot
      security:
      - volunteer_auth:
        - write:volunteer
        - read:volunteer
  /user/login:
    get:
      tags:
      - user
      summary: Logs user into the system
      description: ""
      operationId: loginUser
  /user/logout:
    get:
      tags:
      - user
      summary: Logs out current logged in user session
      description: ""
      operationId: logoutUser
schemes:
- https
- http
...
